# ==============================================================================
# Merged Lakeflow Source: shopify
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import re
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import logging
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current start offset, or None on the first call.
                    PySpark's ``DataSourceStreamReader.latestOffset()`` does not
                    pass this yet, so the framework always sends None for now.
                    Connectors may use it to implement windowed batching when
                    called directly.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/shopify/shopify_schemas.py
    ########################################################

    ADDRESS_STRUCT = StructType(
        [
            StructField("id", LongType(), True),
            StructField("customer_id", LongType(), True),
            StructField("first_name", StringType(), True),
            StructField("last_name", StringType(), True),
            StructField("name", StringType(), True),
            StructField("company", StringType(), True),
            StructField("address1", StringType(), True),
            StructField("address2", StringType(), True),
            StructField("city", StringType(), True),
            StructField("province", StringType(), True),
            StructField("country", StringType(), True),
            StructField("zip", StringType(), True),
            StructField("phone", StringType(), True),
            StructField("province_code", StringType(), True),
            StructField("country_code", StringType(), True),
            StructField("country_name", StringType(), True),
            StructField("default", BooleanType(), True),
        ]
    )

    # Marketing-consent dict shape used by both email and SMS
    MARKETING_CONSENT_STRUCT = StructType(
        [
            StructField("state", StringType(), True),
            StructField("opt_in_level", StringType(), True),
            StructField("consent_updated_at", StringType(), True),
            StructField("consent_collected_from", StringType(), True),
        ]
    )

    # Slimmed customer reference embedded on orders. The full Customer
    # record lives in the `customers` table — keep just enough here to
    # join cleanly without explosion.
    ORDER_CUSTOMER_STRUCT = StructType(
        [
            StructField("id", LongType(), True),
            StructField("email", StringType(), True),
            StructField("first_name", StringType(), True),
            StructField("last_name", StringType(), True),
            StructField("state", StringType(), True),
            StructField("note", StringType(), True),
            StructField("verified_email", BooleanType(), True),
            StructField("currency", StringType(), True),
            StructField("created_at", StringType(), True),
            StructField("updated_at", StringType(), True),
        ]
    )

    # Single line item on an order
    ORDER_LINE_ITEM_STRUCT = StructType(
        [
            StructField("id", LongType(), False),
            StructField("admin_graphql_api_id", StringType(), True),
            StructField("product_id", LongType(), True),
            StructField("variant_id", LongType(), True),
            StructField("title", StringType(), True),
            StructField("variant_title", StringType(), True),
            StructField("name", StringType(), True),
            StructField("sku", StringType(), True),
            StructField("vendor", StringType(), True),
            StructField("quantity", LongType(), True),
            StructField("current_quantity", LongType(), True),
            StructField("fulfillable_quantity", LongType(), True),
            StructField("fulfillment_service", StringType(), True),
            StructField("fulfillment_status", StringType(), True),
            StructField("price", StringType(), True),
            StructField("total_discount", StringType(), True),
            StructField("requires_shipping", BooleanType(), True),
            StructField("taxable", BooleanType(), True),
            StructField("gift_card", BooleanType(), True),
            StructField("grams", LongType(), True),
            StructField("variant_inventory_management", StringType(), True),
            StructField("product_exists", BooleanType(), True),
        ]
    )

    PRODUCT_VARIANT_STRUCT = StructType(
        [
            StructField("id", LongType(), False),
            StructField("admin_graphql_api_id", StringType(), True),
            StructField("product_id", LongType(), True),
            StructField("title", StringType(), True),
            StructField("price", StringType(), True),
            StructField("position", LongType(), True),
            StructField("inventory_policy", StringType(), True),
            StructField("compare_at_price", StringType(), True),
            StructField("option1", StringType(), True),
            StructField("option2", StringType(), True),
            StructField("option3", StringType(), True),
            StructField("created_at", StringType(), True),
            StructField("updated_at", StringType(), True),
            StructField("taxable", BooleanType(), True),
            StructField("barcode", StringType(), True),
            StructField("fulfillment_service", StringType(), True),
            StructField("grams", LongType(), True),
            StructField("inventory_management", StringType(), True),
            StructField("requires_shipping", BooleanType(), True),
            StructField("sku", StringType(), True),
            StructField("weight", DoubleType(), True),
            StructField("weight_unit", StringType(), True),
            StructField("inventory_item_id", LongType(), True),
            StructField("inventory_quantity", LongType(), True),
            StructField("image_id", LongType(), True),
        ]
    )

    PRODUCT_OPTION_STRUCT = StructType(
        [
            StructField("id", LongType(), True),
            StructField("product_id", LongType(), True),
            StructField("name", StringType(), True),
            StructField("position", LongType(), True),
            StructField("values", ArrayType(StringType()), True),
        ]
    )

    PRODUCT_IMAGE_STRUCT = StructType(
        [
            StructField("id", LongType(), True),
            StructField("admin_graphql_api_id", StringType(), True),
            StructField("product_id", LongType(), True),
            StructField("position", LongType(), True),
            StructField("created_at", StringType(), True),
            StructField("updated_at", StringType(), True),
            StructField("alt", StringType(), True),
            StructField("width", LongType(), True),
            StructField("height", LongType(), True),
            StructField("src", StringType(), True),
            StructField("variant_ids", ArrayType(LongType()), True),
        ]
    )

    # Slim refund line item — drops the deeply-nested ``line_item`` mirror
    # (use ``line_item_id`` to join back to ``orders.line_items``).
    REFUND_LINE_ITEM_STRUCT = StructType(
        [
            StructField("id", LongType(), False),
            StructField("line_item_id", LongType(), True),
            StructField("location_id", LongType(), True),
            StructField("quantity", LongType(), True),
            StructField("restock_type", StringType(), True),
            StructField("subtotal", DoubleType(), True),
            StructField("total_tax", DoubleType(), True),
        ]
    )


    # =============================================================================
    # Table Schemas
    # =============================================================================

    TABLE_SCHEMAS: dict[str, StructType] = {
        "locations": StructType(
            [
                StructField("id", LongType(), False),
                StructField("name", StringType(), True),
                StructField("address1", StringType(), True),
                StructField("address2", StringType(), True),
                StructField("city", StringType(), True),
                StructField("zip", StringType(), True),
                StructField("province", StringType(), True),
                StructField("country", StringType(), True),
                StructField("phone", StringType(), True),
                StructField("created_at", StringType(), True),
                StructField("updated_at", StringType(), True),
                StructField("country_code", StringType(), True),
                StructField("country_name", StringType(), True),
                StructField("province_code", StringType(), True),
                StructField("legacy", BooleanType(), True),
                StructField("active", BooleanType(), True),
                StructField("admin_graphql_api_id", StringType(), True),
                StructField("localized_country_name", StringType(), True),
                StructField("localized_province_name", StringType(), True),
                StructField("shop", StringType(), False),
            ]
        ),
        "customers": StructType(
            [
                StructField("id", LongType(), False),
                StructField("email", StringType(), True),
                StructField("first_name", StringType(), True),
                StructField("last_name", StringType(), True),
                StructField("phone", StringType(), True),
                StructField("created_at", StringType(), True),
                StructField("updated_at", StringType(), True),
                StructField("orders_count", LongType(), True),
                StructField("state", StringType(), True),
                StructField("total_spent", StringType(), True),
                StructField("last_order_id", LongType(), True),
                StructField("last_order_name", StringType(), True),
                StructField("note", StringType(), True),
                StructField("verified_email", BooleanType(), True),
                StructField("multipass_identifier", StringType(), True),
                StructField("tax_exempt", BooleanType(), True),
                StructField("tags", StringType(), True),
                StructField("currency", StringType(), True),
                StructField("addresses", ArrayType(ADDRESS_STRUCT), True),
                StructField("default_address", ADDRESS_STRUCT, True),
                StructField("tax_exemptions", ArrayType(StringType()), True),
                StructField(
                    "email_marketing_consent", MARKETING_CONSENT_STRUCT, True
                ),
                StructField(
                    "sms_marketing_consent", MARKETING_CONSENT_STRUCT, True
                ),
                StructField("admin_graphql_api_id", StringType(), True),
                StructField("shop", StringType(), False),
            ]
        ),
        "products": StructType(
            [
                StructField("id", LongType(), False),
                StructField("title", StringType(), True),
                StructField("body_html", StringType(), True),
                StructField("vendor", StringType(), True),
                StructField("product_type", StringType(), True),
                StructField("created_at", StringType(), True),
                StructField("updated_at", StringType(), True),
                StructField("published_at", StringType(), True),
                StructField("handle", StringType(), True),
                StructField("template_suffix", StringType(), True),
                StructField("published_scope", StringType(), True),
                StructField("tags", StringType(), True),
                StructField("status", StringType(), True),
                StructField("admin_graphql_api_id", StringType(), True),
                StructField(
                    "variants", ArrayType(PRODUCT_VARIANT_STRUCT), True
                ),
                StructField(
                    "options", ArrayType(PRODUCT_OPTION_STRUCT), True
                ),
                StructField(
                    "images", ArrayType(PRODUCT_IMAGE_STRUCT), True
                ),
                StructField("image", PRODUCT_IMAGE_STRUCT, True),
                StructField("shop", StringType(), False),
            ]
        ),
        "refunds": StructType(
            [
                StructField("id", LongType(), False),
                StructField("order_id", LongType(), False),
                StructField("created_at", StringType(), True),
                StructField("processed_at", StringType(), True),
                StructField("note", StringType(), True),
                StructField("user_id", LongType(), True),
                StructField("restock", BooleanType(), True),
                StructField("admin_graphql_api_id", StringType(), True),
                StructField(
                    "refund_line_items",
                    ArrayType(REFUND_LINE_ITEM_STRUCT),
                    True,
                ),
                StructField("shop", StringType(), False),
            ]
        ),
        "fulfillments": StructType(
            [
                StructField("id", LongType(), False),
                StructField("order_id", LongType(), False),
                StructField("status", StringType(), True),
                StructField("shipment_status", StringType(), True),
                StructField("service", StringType(), True),
                StructField("created_at", StringType(), True),
                StructField("updated_at", StringType(), True),
                StructField("location_id", LongType(), True),
                StructField("tracking_company", StringType(), True),
                StructField("tracking_number", StringType(), True),
                StructField(
                    "tracking_numbers", ArrayType(StringType()), True
                ),
                StructField("tracking_url", StringType(), True),
                StructField(
                    "tracking_urls", ArrayType(StringType()), True
                ),
                StructField("admin_graphql_api_id", StringType(), True),
                StructField(
                    "line_items", ArrayType(ORDER_LINE_ITEM_STRUCT), True
                ),
                StructField("shop", StringType(), False),
            ]
        ),
        "inventory_levels": StructType(
            [
                StructField("inventory_item_id", LongType(), False),
                StructField("location_id", LongType(), False),
                StructField("available", LongType(), True),
                StructField("updated_at", StringType(), True),
                StructField("admin_graphql_api_id", StringType(), True),
                StructField("shop", StringType(), False),
            ]
        ),
        "orders": StructType(
            [
                StructField("id", LongType(), False),
                StructField("admin_graphql_api_id", StringType(), True),
                StructField("name", StringType(), True),
                StructField("number", LongType(), True),
                StructField("order_number", LongType(), True),
                StructField("email", StringType(), True),
                StructField("phone", StringType(), True),
                StructField("created_at", StringType(), True),
                StructField("updated_at", StringType(), True),
                StructField("processed_at", StringType(), True),
                StructField("closed_at", StringType(), True),
                StructField("cancelled_at", StringType(), True),
                StructField("cancel_reason", StringType(), True),
                StructField("financial_status", StringType(), True),
                StructField("fulfillment_status", StringType(), True),
                StructField("currency", StringType(), True),
                StructField("presentment_currency", StringType(), True),
                StructField("total_price", StringType(), True),
                StructField("subtotal_price", StringType(), True),
                StructField("total_tax", StringType(), True),
                StructField("total_discounts", StringType(), True),
                StructField("total_line_items_price", StringType(), True),
                StructField("total_outstanding", StringType(), True),
                StructField("total_tip_received", StringType(), True),
                StructField("total_weight", LongType(), True),
                StructField("taxes_included", BooleanType(), True),
                StructField("estimated_taxes", BooleanType(), True),
                StructField("duties_included", BooleanType(), True),
                StructField("confirmed", BooleanType(), True),
                StructField("test", BooleanType(), True),
                StructField("buyer_accepts_marketing", BooleanType(), True),
                StructField("tax_exempt", BooleanType(), True),
                StructField("tags", StringType(), True),
                StructField("note", StringType(), True),
                StructField("token", StringType(), True),
                StructField("cart_token", StringType(), True),
                StructField("checkout_id", LongType(), True),
                StructField("checkout_token", StringType(), True),
                StructField("reference", StringType(), True),
                StructField("source_identifier", StringType(), True),
                StructField("source_name", StringType(), True),
                StructField("source_url", StringType(), True),
                StructField("landing_site", StringType(), True),
                StructField("landing_site_ref", StringType(), True),
                StructField("referring_site", StringType(), True),
                StructField("browser_ip", StringType(), True),
                StructField("customer_locale", StringType(), True),
                StructField("location_id", LongType(), True),
                StructField("user_id", LongType(), True),
                StructField("device_id", LongType(), True),
                StructField("app_id", LongType(), True),
                StructField("po_number", StringType(), True),
                StructField("confirmation_number", StringType(), True),
                StructField(
                    "payment_gateway_names", ArrayType(StringType()), True
                ),
                StructField("customer", ORDER_CUSTOMER_STRUCT, True),
                StructField("shipping_address", ADDRESS_STRUCT, True),
                StructField("billing_address", ADDRESS_STRUCT, True),
                StructField(
                    "line_items", ArrayType(ORDER_LINE_ITEM_STRUCT), True
                ),
                StructField("shop", StringType(), False),
            ]
        ),
    }


    # =============================================================================
    # Table Metadata
    # =============================================================================

    TABLE_METADATA: dict[str, dict] = {
        "locations": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "customers": {
            "primary_keys": ["id"],
            "cursor_field": "updated_at",
            "ingestion_type": "cdc",
        },
        "products": {
            "primary_keys": ["id"],
            "cursor_field": "updated_at",
            "ingestion_type": "cdc",
        },
        "orders": {
            "primary_keys": ["id"],
            "cursor_field": "updated_at",
            "ingestion_type": "cdc",
        },
        "refunds": {
            "primary_keys": ["id"],
            "cursor_field": "created_at",
            "ingestion_type": "append",
        },
        "fulfillments": {
            "primary_keys": ["id"],
            "cursor_field": "updated_at",
            "ingestion_type": "cdc",
        },
        "inventory_levels": {
            "primary_keys": ["inventory_item_id", "location_id"],
            "cursor_field": "updated_at",
            "ingestion_type": "cdc",
        },
    }


    SUPPORTED_TABLES: list[str] = list(TABLE_SCHEMAS.keys())


    ########################################################
    # src/databricks/labs/community_connector/sources/shopify/shopify_utils.py
    ########################################################

    RETRIABLE_STATUS_CODES = {429, 500, 502, 503, 504}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 1.0  # seconds; doubled after each retry


    def request_with_retry(
        session: requests.Session,
        url: str,
        params: dict[str, str] | None = None,
    ) -> requests.Response:
        """Issue a GET with exponential backoff on retriable errors.

        Honors the ``Retry-After`` header when present (Shopify returns this
        on 429 with a value in seconds), otherwise doubles the backoff
        (1, 2, 4, 8, 16 s).
        """
        backoff = INITIAL_BACKOFF
        resp = None
        for attempt in range(MAX_RETRIES):
            resp = session.get(url, params=params, timeout=30)
            if resp.status_code not in RETRIABLE_STATUS_CODES:
                return resp

            if attempt < MAX_RETRIES - 1:
                retry_after = resp.headers.get("Retry-After")
                try:
                    wait = float(retry_after) if retry_after else backoff
                except (TypeError, ValueError):
                    wait = backoff
                time.sleep(wait)
                backoff *= 2

        return resp


    def api_get(
        session: requests.Session,
        url: str,
        params: dict[str, str] | None,
        label: str,
    ) -> tuple[dict[str, Any], requests.Response]:
        """GET a Shopify endpoint and return (json_body, response).

        Returns the response too so callers can extract the Link header for
        cursor pagination.

        Raises RuntimeError on non-200 status with a descriptive label.
        """
        response = request_with_retry(session, url, params)
        if response.status_code != 200:
            raise RuntimeError(
                f"Shopify API error for {label}: "
                f"{response.status_code} {response.text}"
            )
        return response.json(), response


    # --------------------------------------------------------------------------- #
    # Link-header cursor pagination
    # --------------------------------------------------------------------------- #

    # Shopify returns pagination cursors in the Link response header, e.g.:
    #   Link: <https://shop.myshopify.com/admin/api/2026-04/products.json
    #          ?page_info=hijgklmn&limit=50>; rel="next"
    # We extract the next-page URL (or just the page_info value) for the next call.
    _NEXT_LINK_RE = re.compile(r'<([^>]+)>;\s*rel="next"')


    def extract_next_link(response: requests.Response) -> str | None:
        """Return the next-page URL from a Shopify Link response header.

        Returns ``None`` when there is no next page (i.e. drained).
        """
        link = response.headers.get("Link")
        if not link:
            return None
        match = _NEXT_LINK_RE.search(link)
        return match.group(1) if match else None


    def nullify_empty(record: dict, *keys: str) -> None:
        """Replace missing or empty-dict nested structs with ``None``."""
        for key in keys:
            if key not in record or record[key] == {}:
                record[key] = None


    def paginate_get(
        session: requests.Session,
        initial_url: str,
        initial_params: dict[str, str] | None,
        label: str,
        response_key: str,
    ):
        """Yield records by following Shopify Link-header cursor pagination.

        Initial call uses *initial_url* + *initial_params*. Subsequent
        calls follow the next-page URL from the Link header verbatim
        (Shopify's docs are explicit: only ``limit`` and ``fields`` are
        permitted alongside a ``page_info`` cursor; all original filter
        params are encoded in the cursor itself).
        """
        url, params = initial_url, initial_params
        while url:
            data, response = api_get(session, url, params, label)
            for record in data.get(response_key, []):
                yield record
            url = extract_next_link(response)
            # After the first page the cursor URL embeds all filter params,
            # so subsequent calls pass no params of their own.
            params = None


    ########################################################
    # src/databricks/labs/community_connector/sources/shopify/shopify.py
    ########################################################

    _LOG = logging.getLogger(__name__)

    DEFAULT_API_VERSION = "2026-04"


    class ShopifyLakeflowConnect(LakeflowConnect):
        """Shopify Admin REST API connector.

        Auth: Admin API access token (custom-app token, format ``shpat_...``).
        Pagination: Link-header cursor pagination (``page_info`` parameter).
        Versioning: API version pinned via the ``api_version`` connection
        option; defaults to the latest stable version supported by this
        connector.

        See ``shopify_api_doc.md`` for endpoint specifics, scope mapping,
        rate-limit behavior, and per-table edge cases.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """Initialize the Shopify connector.

            Expected options:
                - shop: Shopify shop subdomain (e.g. ``"lakeflow-test-store"``)
                - access_token: Admin API access token
                - api_version: API version string (optional, default ``2026-04``)
            """
            shop = options.get("shop")
            access_token = options.get("access_token")
            api_version = options.get("api_version") or DEFAULT_API_VERSION

            if not shop:
                raise ValueError("Shopify connector requires 'shop'")
            if not access_token:
                raise ValueError("Shopify connector requires 'access_token'")

            self.shop = shop
            self.api_version = api_version
            self.base_url = (
                f"https://{shop}.myshopify.com/admin/api/{api_version}"
            )

            self._session = requests.Session()
            self._session.headers.update(
                {
                    "X-Shopify-Access-Token": access_token,
                    "Accept": "application/json",
                }
            )

        # ------------------------------------------------------------------ #
        # Interface methods
        # ------------------------------------------------------------------ #

        def list_tables(self) -> list[str]:
            return SUPPORTED_TABLES

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            if table_name not in TABLE_SCHEMAS:
                raise ValueError(f"Unsupported table: {table_name!r}")
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            if table_name not in TABLE_METADATA:
                raise ValueError(f"Unsupported table: {table_name!r}")
            return TABLE_METADATA[table_name]

        def read_table(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            dispatch = {
                "locations": self._read_locations,
                "customers": self._read_customers,
                "products": self._read_products,
                "orders": self._read_orders,
                "refunds": self._read_refunds,
                "fulfillments": self._read_fulfillments,
                "inventory_levels": self._read_inventory_levels,
            }
            handler = dispatch.get(table_name)
            if handler is None:
                raise ValueError(f"Unsupported table: {table_name!r}")
            return handler(start_offset, table_options)

        # ------------------------------------------------------------------ #
        # Table readers
        # ------------------------------------------------------------------ #

        def _read_locations(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read locations as a snapshot (no pagination, no incremental).

            Locations endpoint has no incremental filter and no cursor
            pagination — Shopify caps the response at the full set, which
            is small for almost all merchants. Snapshot ingestion is the
            right fit.
            """
            data, _ = api_get(
                self._session,
                f"{self.base_url}/locations.json",
                params=None,
                label="locations",
            )
            records: list[dict[str, Any]] = []
            for loc in data.get("locations", []):
                rec = dict(loc)
                rec["shop"] = self.shop
                records.append(rec)
            return iter(records), {}

        # -- CDC tables (customers, products, orders) ---------------------- #

        def _read_cdc_table(
            self,
            start_offset: dict,
            table_name: str,
            response_key: str,
            extra_params: dict[str, str] | None = None,
        ) -> tuple[Iterator[dict], dict]:
            """Generic CDC reader using ``updated_at`` watermark.

            - Uses Shopify's ``updated_at_min`` server-side filter (inclusive)
            - Client-side strict ``> watermark`` to make filter exclusive for
              stable termination semantics
            - Watermark advances to ``max(updated_at)`` across returned records,
              so ``end_offset == start_offset`` exactly when no records have
              changed since the last sync
            - Pagination via Link-header cursor (``page_info``) — see utils
            """
            start_offset = start_offset or {}
            since: str | None = start_offset.get("updated_at")

            params: dict[str, str] = {"limit": "250"}
            if extra_params:
                params.update(extra_params)
            if since:
                params["updated_at_min"] = since

            url = f"{self.base_url}/{table_name}.json"

            records: list[dict[str, Any]] = []
            max_seen: str | None = since
            for raw in paginate_get(
                self._session, url, params, table_name, response_key
            ):
                rec_updated = raw.get("updated_at")
                # Strict `>` to keep boundary records from re-emitting on
                # every run (Shopify's filter is inclusive).
                if since and rec_updated and rec_updated <= since:
                    continue
                rec = dict(raw)
                rec["shop"] = self.shop
                records.append(rec)
                if rec_updated and (
                    max_seen is None or rec_updated > max_seen
                ):
                    max_seen = rec_updated

            end_offset = {"updated_at": max_seen} if max_seen else {}
            return iter(records), end_offset

        def _read_customers(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            return self._read_cdc_table(
                start_offset,
                table_name="customers",
                response_key="customers",
            )

        def _read_products(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            return self._read_cdc_table(
                start_offset,
                table_name="products",
                response_key="products",
            )

        def _read_orders(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            # Default `status=any` so cancelled / closed orders are
            # included — Shopify's default of `status=open` would silently
            # drop them. See shopify_api_doc.md for the gotcha.
            return self._read_cdc_table(
                start_offset,
                table_name="orders",
                response_key="orders",
                extra_params={"status": "any"},
            )

        # -- Per-order child resources (refunds, fulfillments) ------------- #

        def _read_per_order_table(
            self,
            start_offset: dict,
            sub_resource: str,
            cursor_field: str,
        ) -> tuple[Iterator[dict], dict]:
            """Read a per-order child resource using the parent-orders trick.

            The /orders/{id}/{sub_resource}.json endpoints don't accept a
            date filter, so we discover candidate orders via the orders
            endpoint with ``updated_at_min=watermark`` (Shopify's order
            ``updated_at`` advances when refunds/fulfillments are added),
            then fetch the sub-resource for each candidate. Records are
            finally filtered client-side by ``cursor_field > watermark``.
            """
            start_offset = start_offset or {}
            since: str | None = start_offset.get(cursor_field)

            orders_params: dict[str, str] = {
                "limit": "250",
                "status": "any",
            }
            if since:
                orders_params["updated_at_min"] = since

            all_records: list[dict[str, Any]] = []
            max_seen: str | None = since

            for order in paginate_get(
                self._session,
                f"{self.base_url}/orders.json",
                orders_params,
                f"{sub_resource}-discovery",
                "orders",
            ):
                order_id = order.get("id")
                if not order_id:
                    continue
                try:
                    data, _ = api_get(
                        self._session,
                        f"{self.base_url}/orders/{order_id}/{sub_resource}.json",
                        params=None,
                        label=sub_resource,
                    )
                except RuntimeError as exc:
                    # Skip individual orders that fail (e.g. permissions on a
                    # specific order) so the whole batch doesn't blow up.
                    _LOG.warning(
                        "Skipping %s for order %s: %s",
                        sub_resource, order_id, exc,
                    )
                    continue
                for item in data.get(sub_resource, []):
                    ts = item.get(cursor_field)
                    if since and ts and ts <= since:
                        continue
                    rec = dict(item)
                    rec["shop"] = self.shop
                    all_records.append(rec)
                    if ts and (max_seen is None or ts > max_seen):
                        max_seen = ts

            end_offset = {cursor_field: max_seen} if max_seen else {}
            return iter(all_records), end_offset

        def _read_refunds(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            return self._read_per_order_table(
                start_offset,
                sub_resource="refunds",
                cursor_field="created_at",
            )

        def _read_fulfillments(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            return self._read_per_order_table(
                start_offset,
                sub_resource="fulfillments",
                cursor_field="updated_at",
            )

        # -- Inventory ----------------------------------------------------- #

        def _read_inventory_levels(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read inventory levels across all locations.

            The /inventory_levels.json endpoint requires ``location_ids``
            or ``inventory_item_ids`` as a query param, so we first list
            locations and then iterate. The endpoint has no date filter,
            so we fetch all levels each run; the framework's CDC merge on
            the composite ``(inventory_item_id, location_id)`` PK handles
            deltas idempotently. Watermark advances to ``max(updated_at)``
            across returned records to signal forward progress when data
            actually changed.
            """
            start_offset = start_offset or {}
            max_seen: str | None = start_offset.get("updated_at")

            locs_data, _ = api_get(
                self._session,
                f"{self.base_url}/locations.json",
                params=None,
                label="locations",
            )
            location_ids = [
                str(loc["id"])
                for loc in locs_data.get("locations", [])
                if loc.get("id") and loc.get("active")
            ]

            all_records: list[dict[str, Any]] = []
            for loc_id in location_ids:
                for level in paginate_get(
                    self._session,
                    f"{self.base_url}/inventory_levels.json",
                    {"limit": "250", "location_ids": loc_id},
                    "inventory_levels",
                    "inventory_levels",
                ):
                    rec = dict(level)
                    rec["shop"] = self.shop
                    all_records.append(rec)
                    ts = level.get("updated_at")
                    if ts and (max_seen is None or ts > max_seen):
                        max_seen = ts

            end_offset = {"updated_at": max_seen} if max_seen else {}
            return iter(all_records), end_offset


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = ShopifyLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowPartitionedStreamReader(DataSourceStreamReader):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def latestOffset(self):
            # PySpark does not pass the current offset to latestOffset() yet,
            # so we forward None.  Once PySpark supports it, pass the real value.
            return self.lakeflow_connect.latest_offset(self.table_name, self.table_options, None)

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name != METADATA_TABLE:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
