# ==============================================================================
# Merged Lakeflow Source: collibra
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import logging
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/collibra/collibra_schemas.py
    ########################################################

    RESOURCE_REF_STRUCT = StructType(
        [
            StructField("id", StringType(), True),
            StructField("name", StringType(), True),
            StructField("resourceType", StringType(), True),
            StructField("resourceDiscriminator", StringType(), True),
        ]
    )


    # =============================================================================
    # Table schemas
    # =============================================================================

    ASSETS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("createdBy", StringType(), True),
            StructField("createdOn", LongType(), True),
            StructField("lastModifiedBy", StringType(), True),
            StructField("lastModifiedOn", LongType(), True),
            StructField("system", BooleanType(), True),
            StructField("name", StringType(), True),
            StructField("displayName", StringType(), True),
            StructField("articulationScore", DoubleType(), True),
            StructField("excludedFromAutoHyperlinking", BooleanType(), True),
            StructField("domain", RESOURCE_REF_STRUCT, True),
            StructField("type", RESOURCE_REF_STRUCT, True),
            StructField("status", RESOURCE_REF_STRUCT, True),
            StructField("avgRating", DoubleType(), True),
            StructField("ratingsCount", IntegerType(), True),
            StructField("collibra_org", StringType(), False),
        ]
    )

    ATTRIBUTES_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("createdBy", StringType(), True),
            StructField("createdOn", LongType(), True),
            StructField("lastModifiedBy", StringType(), True),
            StructField("lastModifiedOn", LongType(), True),
            StructField("system", BooleanType(), True),
            StructField("attributeDiscriminator", StringType(), True),
            # Polymorphic value kept as a raw string; use attributeDiscriminator
            # downstream to coerce (StringAttribute / BooleanAttribute / ...).
            StructField("value", StringType(), True),
            StructField("type", RESOURCE_REF_STRUCT, True),
            StructField("asset", RESOURCE_REF_STRUCT, True),
            StructField("collibra_org", StringType(), False),
        ]
    )

    RESPONSIBILITIES_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("createdBy", StringType(), True),
            StructField("createdOn", LongType(), True),
            StructField("lastModifiedBy", StringType(), True),
            StructField("lastModifiedOn", LongType(), True),
            StructField("system", BooleanType(), True),
            StructField("role", RESOURCE_REF_STRUCT, True),
            # baseResource is where the role was directly assigned (asset, domain,
            # or community). For inherited responsibilities this points at the
            # parent, not the asset — see collibra_api_doc.md gotcha #1.
            StructField("baseResource", RESOURCE_REF_STRUCT, True),
            # owner.resourceDiscriminator is "User" or "Group".
            StructField("owner", RESOURCE_REF_STRUCT, True),
            StructField("collibra_org", StringType(), False),
        ]
    )

    DOMAINS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("createdBy", StringType(), True),
            StructField("createdOn", LongType(), True),
            StructField("lastModifiedBy", StringType(), True),
            StructField("lastModifiedOn", LongType(), True),
            StructField("system", BooleanType(), True),
            StructField("name", StringType(), True),
            # Domain description is a native field (not stored as an attribute).
            StructField("description", StringType(), True),
            StructField("meta", BooleanType(), True),
            StructField("excludedFromAutoHyperlinking", BooleanType(), True),
            StructField("community", RESOURCE_REF_STRUCT, True),
            StructField("type", RESOURCE_REF_STRUCT, True),
            StructField("collibra_org", StringType(), False),
        ]
    )


    TABLE_SCHEMAS: dict[str, StructType] = {
        "assets": ASSETS_SCHEMA,
        "attributes": ATTRIBUTES_SCHEMA,
        "responsibilities": RESPONSIBILITIES_SCHEMA,
        "domains": DOMAINS_SCHEMA,
    }


    # =============================================================================
    # Table metadata
    # =============================================================================

    TABLE_METADATA: dict[str, dict] = {
        "assets": {
            "primary_keys": ["id"],
            "cursor_field": "lastModifiedOn",
            "ingestion_type": "cdc",
        },
        "attributes": {
            "primary_keys": ["id"],
            "cursor_field": "lastModifiedOn",
            "ingestion_type": "cdc",
        },
        "responsibilities": {
            "primary_keys": ["id"],
            "cursor_field": "lastModifiedOn",
            "ingestion_type": "cdc",
        },
        "domains": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
    }


    SUPPORTED_TABLES: list[str] = list(TABLE_SCHEMAS.keys())


    # =============================================================================
    # HTTP retry tuning
    # =============================================================================

    RETRIABLE_STATUS_CODES = {429, 500, 502, 503, 504}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 1.0  # seconds; doubled after each retry

    # Collibra caps page size at 1000 across all endpoints.
    MAX_PAGE_SIZE = 1000
    DEFAULT_PAGE_SIZE = 1000


    ########################################################
    # src/databricks/labs/community_connector/sources/collibra/collibra_utils.py
    ########################################################

    DEFAULT_TIMEOUT = 30  # seconds


    def request_with_retry(
        session: requests.Session,
        url: str,
        params: dict[str, str] | None = None,
        timeout: int = DEFAULT_TIMEOUT,
    ) -> requests.Response:
        """Issue a GET with exponential backoff on retriable status codes.

        Honors the ``Retry-After`` header when present, otherwise doubles the
        backoff (1, 2, 4, 8, 16 s). Always passes an explicit ``timeout``.
        """
        backoff = INITIAL_BACKOFF
        resp = None
        for attempt in range(MAX_RETRIES):
            resp = session.get(url, params=params, timeout=timeout)
            if resp.status_code not in RETRIABLE_STATUS_CODES:
                return resp

            if attempt < MAX_RETRIES - 1:
                retry_after = resp.headers.get("Retry-After")
                try:
                    wait = float(retry_after) if retry_after else backoff
                except (TypeError, ValueError):
                    wait = backoff
                time.sleep(wait)
                backoff *= 2

        return resp


    def api_get(
        session: requests.Session,
        url: str,
        params: dict[str, str],
        label: str,
        timeout: int = DEFAULT_TIMEOUT,
    ) -> dict:
        """GET and return parsed JSON, raising RuntimeError on non-200 responses."""
        response = request_with_retry(session, url, params, timeout=timeout)
        if response.status_code != 200:
            raise RuntimeError(
                f"Collibra API error for {label}: "
                f"{response.status_code} {response.text}"
            )
        return response.json()


    def cursor_paginate(
        session: requests.Session,
        url: str,
        params: dict[str, str],
        label: str,
        records_key: str = "results",
        *,
        timeout: int = DEFAULT_TIMEOUT,
    ) -> Iterator[dict[str, Any]]:
        """Yield records from a cursor-paginated Collibra endpoint.

        Starts with ``cursor=""`` (empty string, first page) and follows the
        ``nextCursor`` field in each response body until it is absent. Used for
        ``/assets``, ``/attributes``, and ``/domains``.

        NOTE (needs-live-testing): The exact cursor mechanism for ``/assets``
        differs from ``/attributes`` per the API docs — ``/attributes`` returns
        ``nextCursor`` explicitly, while ``/assets`` may require ID-keyset
        pagination (sort by ``ID ASC``, filter ``id > last_seen_id``). This helper
        follows ``nextCursor`` uniformly; confirm on a live instance and switch
        ``/assets`` to keyset pagination if ``nextCursor`` is not returned.
        """
        page_params = dict(params)
        page_params.setdefault("cursor", "")
        while True:
            body = api_get(session, url, page_params, label, timeout=timeout)
            batch = body.get(records_key, []) or []
            yield from batch

            next_cursor = body.get("nextCursor")
            if not next_cursor or not batch:
                break
            page_params["cursor"] = next_cursor


    def cursor_paginate_pages(
        session: requests.Session,
        url: str,
        params: dict[str, str],
        label: str,
        records_key: str = "results",
        *,
        start_cursor: str = "",
        timeout: int = DEFAULT_TIMEOUT,
    ) -> Iterator[tuple[list[dict[str, Any]], str | None]]:
        """Like ``cursor_paginate`` but yields whole pages with their resume token.

        Yields ``(batch, next_cursor)`` per page, where ``next_cursor`` is the
        opaque ``nextCursor`` to resume *after* this page (``None`` on the last
        page). Lets a caller stop at a page boundary and persist ``next_cursor`` as
        a durable resume point — the basis for resumable ``/assets`` ingest (the
        cursor is an ID-keyset token, so resuming from it is exact). ``start_cursor``
        begins pagination partway through (``""`` = first page).
        """
        page_params = dict(params)
        page_params["cursor"] = start_cursor
        while True:
            body = api_get(session, url, page_params, label, timeout=timeout)
            batch = body.get(records_key, []) or []
            next_cursor = body.get("nextCursor")
            # Normalize the "no more pages" signal to None.
            if not next_cursor or not batch:
                yield batch, None
                break
            yield batch, next_cursor
            page_params["cursor"] = next_cursor


    def offset_paginate(
        session: requests.Session,
        url: str,
        params: dict[str, str],
        label: str,
        *,
        page_size: int,
        records_key: str = "results",
        timeout: int = DEFAULT_TIMEOUT,
    ) -> Iterator[dict[str, Any]]:
        """Yield records from an offset/limit-paginated Collibra endpoint.

        Advances ``offset`` by ``page_size`` until a short page (fewer than
        ``page_size`` records) signals the end. Used for ``/responsibilities``,
        which does not support cursor pagination.
        """
        offset = 0
        while True:
            page_params = dict(params)
            page_params["offset"] = str(offset)
            page_params["limit"] = str(page_size)

            body = api_get(session, url, page_params, label, timeout=timeout)
            batch = body.get(records_key, []) or []
            yield from batch

            if len(batch) < page_size:
                break
            offset += page_size


    def resource_ref(value: Any) -> dict[str, Any] | None:
        """Normalize a nested resource reference to the declared struct shape.

        Returns ``None`` for absent/empty references (rather than an empty dict)
        so the field maps cleanly onto the nullable struct, and keeps only the
        declared keys so extra API fields don't break schema coercion.
        """
        if not isinstance(value, dict) or not value:
            return None
        return {
            "id": value.get("id"),
            "name": value.get("name"),
            "resourceType": value.get("resourceType"),
            "resourceDiscriminator": value.get("resourceDiscriminator"),
        }


    ########################################################
    # src/databricks/labs/community_connector/sources/collibra/collibra.py
    ########################################################

    _LOG = logging.getLogger(__name__)

    DEFAULT_MAX_RECORDS_PER_BATCH = 5000


    class CollibraLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for Collibra Core REST API v2."""

        def __init__(self, options: dict[str, str]) -> None:
            """Initialize the Collibra connector.

            Expected options:
                - org: Collibra Cloud subdomain (e.g. ``"databricks"`` for
                  ``https://databricks.collibra.com``). Alternatively pass
                  ``base_url`` with the full REST base
                  (``https://{org}.collibra.com/rest/2.0``).
                - access_token: OAuth 2.0 bearer token, minted and injected by
                  the UC COMMUNITY connection (m2m / client-credentials).
                - token: personal/API token fallback used the same way as
                  ``access_token`` (``Authorization: Bearer``) for ad-hoc use.
            """
            super().__init__(options)

            base_url = options.get("base_url")
            org = options.get("org")

            if base_url:
                self.base_url = base_url.rstrip("/")
                # Derive a stable org label from the host for row disambiguation.
                self.org = org or self._org_from_base_url(self.base_url)
            elif org:
                self.org = org
                self.base_url = f"https://{org}.collibra.com/rest/2.0"
            else:
                raise ValueError(
                    "Collibra connector requires 'org' (Collibra subdomain) "
                    "or 'base_url' (full REST base URL)"
                )

            try:
                self._page_size = max(
                    1,
                    min(
                        MAX_PAGE_SIZE,
                        int(options.get("page_size") or DEFAULT_PAGE_SIZE),
                    ),
                )
            except (TypeError, ValueError):
                self._page_size = DEFAULT_PAGE_SIZE

            self._session = requests.Session()
            self._session.headers.update({"Accept": "application/json"})
            self._configure_auth(options)

            # Cap incremental cursors at init time so a single Trigger.AvailableNow
            # run only drains data that existed when the connector started; data
            # modified after this point is picked up by the next trigger with a
            # fresh _init_ts. This is the termination guard. Epoch milliseconds to
            # match Collibra's lastModifiedOn cursor unit.
            self._init_ts = int(datetime.now(timezone.utc).timestamp() * 1000)

        def _configure_auth(self, options: dict[str, str]) -> None:
            """Set the Bearer auth header from the injected token.

            ``access_token`` (OAuth m2m, UC-injected) takes precedence; ``token``
            is an equivalent personal-token fallback. The connector never runs the
            OAuth client-credentials exchange itself — that is offloaded to Unity
            Catalog, mirroring the Azure DevOps ``service_principal`` model.
            """
            access_token = options.get("access_token") or options.get("token")
            if not access_token:
                raise ValueError(
                    "Collibra connector requires 'access_token' (OAuth m2m "
                    "bearer token, injected by the UC connection) or 'token'"
                )
            self._session.headers["Authorization"] = f"Bearer {access_token}"

        @staticmethod
        def _org_from_base_url(base_url: str) -> str:
            """Best-effort extraction of the org subdomain from a base URL."""
            try:
                host = base_url.split("://", 1)[-1].split("/", 1)[0]
                return host.split(".", 1)[0]
            except (IndexError, AttributeError):
                return base_url

        # ------------------------------------------------------------------ #
        # Interface methods
        # ------------------------------------------------------------------ #

        def list_tables(self) -> list[str]:
            return list(SUPPORTED_TABLES)

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            self._validate_table(table_name)
            return dict(TABLE_METADATA[table_name])

        def read_table(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            self._validate_table(table_name)
            if table_name == "assets":
                return self._read_assets(start_offset, table_options)
            if table_name == "attributes":
                return self._read_attributes(start_offset, table_options)
            if table_name == "responsibilities":
                return self._read_responsibilities(start_offset, table_options)
            if table_name == "domains":
                return self._read_domains(table_options)
            raise ValueError(f"Unsupported table: {table_name!r}")

        # ------------------------------------------------------------------ #
        # Table readers
        # ------------------------------------------------------------------ #

        def _read_assets(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read assets incrementally on the ``lastModifiedOn`` cursor.

            ``sortField`` is required on ``/assets``. Live-validated
            (databricks.collibra.com, 2026-07-25): ``/assets`` accepts ONLY
            ``NAME`` / ``DISPLAY_NAME`` / ``ID`` — ``LAST_MODIFIED`` is rejected
            (400); that value is valid only on ``/responsibilities`` and
            ``/relations``. We therefore default to ``ID`` (stable keyset order),
            and the ``lastModifiedOn`` incremental cursor is applied CLIENT-SIDE
            (see ``_read_cdc_incremental``) rather than relying on server ordering.
            Overridable via the ``sort_field`` table option (NAME/DISPLAY_NAME/ID).
            """
            sort_field = table_options.get("sort_field", "ID")
            base_params = {
                "limit": str(self._page_size),
                "sortField": sort_field,
                "sortOrder": "ASC",
                # Fast path: skip the expensive count query (see gotcha #2).
                "countLimit": "0",
            }
            if table_options.get("domain_id"):
                base_params["domainId"] = table_options["domain_id"]
            if table_options.get("community_id"):
                base_params["communityId"] = table_options["community_id"]

            # `/assets` is keyset-paginated by the sort field (LAST_MODIFIED is
            # rejected 400), so records do NOT arrive in lastModifiedOn order and a
            # count-based batch cap cannot safely advance the lastModifiedOn
            # watermark. Two strategies:
            #
            #   * sort_field == "ID" (default, UNIQUE keyset): use the resumable
            #     path — page by the opaque nextCursor (which is an `AFTER:id:`
            #     keyset token), honor max_records_per_batch as a page-granular cap,
            #     and only advance the lastModifiedOn watermark when a full id-pass
            #     completes. This lets a run killed mid-collection (e.g. m2m token
            #     expiry on a large full-load) resume from the last page instead of
            #     restarting. See `_incremental_assets_resumable`.
            #   * sort_field in {NAME, DISPLAY_NAME} (NON-unique): fall back to the
            #     full-drain path (ignore the cap, drain the whole collection per
            #     run bounded by _init_ts). A non-unique sort key can't be a safe
            #     resume cursor, so we don't batch it.
            if sort_field == "ID":
                return self._incremental_assets_resumable(
                    base_params, start_offset, table_options
                )

            record_iter = cursor_paginate(
                self._session, f"{self.base_url}/assets", base_params, "assets"
            )
            return self._incremental_from_iter(
                record_iter, start_offset, table_options, cursor_sorted=False
            )

        def _read_attributes(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read attributes incrementally on the ``lastModifiedOn`` cursor.

            The ``value`` field is polymorphic (keyed off
            ``attributeDiscriminator``); we keep the raw value coerced to a
            string plus the discriminator and defer any typed join downstream.
            """
            base_params = {
                "limit": str(self._page_size),
                "sortField": "LAST_MODIFIED",
                "sortOrder": "ASC",
            }
            if table_options.get("asset_id"):
                base_params["assetId"] = table_options["asset_id"]
            if table_options.get("type_public_ids"):
                base_params["typePublicIds"] = table_options["type_public_ids"]

            record_iter = cursor_paginate(
                self._session,
                f"{self.base_url}/attributes",
                base_params,
                "attributes",
            )
            return self._incremental_from_iter(
                record_iter, start_offset, table_options, transform=self._shape_attribute
            )

        def _read_responsibilities(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read responsibilities incrementally (offset/limit paginated).

            ``/responsibilities`` does not support cursor pagination, so we page
            by offset. ``includeInherited=true`` is set explicitly — without it
            domain/community-level owner assignments that apply to child assets
            are dropped (gotcha #1).
            """
            base_params = {
                "sortField": "LAST_MODIFIED",
                "sortOrder": "ASC",
                "includeInherited": "true",
            }
            if table_options.get("resource_ids"):
                base_params["resourceIds"] = table_options["resource_ids"]
            if table_options.get("role_ids"):
                # needs-live-testing: role UUIDs for Data Owner / Data Steward /
                # SME are environment-specific; pass them through when supplied.
                base_params["roleIds"] = table_options["role_ids"]

            record_iter = offset_paginate(
                self._session,
                f"{self.base_url}/responsibilities",
                base_params,
                "responsibilities",
                page_size=self._page_size,
            )
            return self._incremental_from_iter(
                record_iter, start_offset, table_options,
                transform=self._shape_responsibility,
            )

        def _read_domains(
            self, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read domains as a snapshot (cursor-paginated, full read)."""
            base_params = {"limit": str(self._page_size)}
            if table_options.get("community_id"):
                base_params["communityId"] = table_options["community_id"]

            records: list[dict[str, Any]] = []
            for raw in cursor_paginate(
                self._session, f"{self.base_url}/domains", base_params, "domains"
            ):
                records.append(self._shape_domain(raw))
            return iter(records), {}

        # ------------------------------------------------------------------ #
        # Incremental engine
        # ------------------------------------------------------------------ #

        def _incremental_from_iter(
            self,
            record_iter: Iterator[dict[str, Any]],
            start_offset: dict,
            table_options: dict[str, str],
            transform=None,
            *,
            cursor_sorted: bool = True,
        ) -> tuple[Iterator[dict], dict]:
            """Apply the client-side incremental cursor over a record iterator.

            Applies, per record:
              * strict ``> since`` filtering (exclusive lower bound),
              * an init-time upper cap (skip records modified after
                ``self._init_ts``) so Trigger.AvailableNow terminates.

            Truncation depends on the underlying sort order:

            * ``cursor_sorted=True`` (``attributes`` / ``responsibilities`` —
              server-sorted ``LAST_MODIFIED ASC``): ``max_records_per_batch`` acts
              as a **soft** limit. Once the cap is reached we keep draining records
              that share the current max ``lastModifiedOn`` (the boundary tie
              group) before stopping, so the batch never splits a group sharing one
              cursor value. Splitting it would advance the watermark to that value
              and the next run's strict ``> since`` filter would permanently skip
              the un-emitted remainder of the group.

            * ``cursor_sorted=False`` (``assets`` — sorted by ``ID``, because
              ``/assets`` rejects ``LAST_MODIFIED``): records do **not** arrive in
              ``lastModifiedOn`` order, so no count-based truncation can safely
              advance the ``lastModifiedOn`` watermark (a partial ID-ordered slice
              has an arbitrary max cursor; advancing to it silently drops every
              not-yet-seen asset modified at or before it). We therefore ignore
              ``max_records`` and drain the full collection, bounded only by the
              ``self._init_ts`` upper cap; ``max_seen`` is then the true max over
              the whole scan. (A resumable ID-keyset cursor is the follow-up that
              would let this path batch safely — see README.)

            Returns ``(records, end_offset)``. When nothing new is emitted, the
            offset is returned unchanged so ``end_offset == start_offset`` and the
            trigger converges.
            """
            start_offset = start_offset or {}
            since = start_offset.get("cursor")

            # Already caught up to init time — nothing new can be emitted.
            if since is not None and self._as_cursor(since) is not None:
                since_val = self._as_cursor(since)
                if since_val >= self._init_ts:
                    return iter([]), start_offset
            else:
                since_val = None

            # Count-based truncation is only sound when records arrive in cursor
            # order (see the assets note above).
            max_records = self._parse_max_records(table_options) if cursor_sorted else None

            records: list[dict[str, Any]] = []
            max_seen = since_val
            capped = False
            for raw in record_iter:
                cursor = self._as_cursor(raw.get("lastModifiedOn"))
                # Strict `>` so the inclusive nature of a resumed `since` doesn't
                # re-emit the boundary record.
                if since_val is not None and cursor is not None and cursor <= since_val:
                    continue
                # Init-time cap: skip records modified after the connector started.
                if cursor is not None and cursor > self._init_ts:
                    continue

                # Soft cap: past the limit we only keep draining the boundary tie
                # group; the first record with a strictly greater cursor ends it.
                if capped and cursor is not None and max_seen is not None and cursor > max_seen:
                    break

                rec = transform(raw) if transform else self._shape_asset(raw)
                records.append(rec)
                if cursor is not None and (max_seen is None or cursor > max_seen):
                    max_seen = cursor

                if max_records is not None and len(records) >= max_records:
                    capped = True

            if not records or max_seen is None or max_seen == since_val:
                # No forward progress — return the offset unchanged so the
                # framework sees end_offset == start_offset and terminates.
                return iter(records), start_offset

            return iter(records), {"cursor": max_seen}

        def _incremental_assets_resumable(
            self,
            base_params: dict[str, str],
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Resumable incremental read for the ID-sorted ``assets`` path.

            ``/assets`` is keyset-paginated by ``id`` (its opaque ``nextCursor`` is
            an ``AFTER:id:<id>`` token), but filtered incrementally on
            ``lastModifiedOn``. Those are two independent dimensions, so we track
            them separately in the offset:

              * ``cursor``     — the committed ``lastModifiedOn`` watermark (floor).
                                 Only advances when a full id-pass completes.
              * ``page_token`` — the opaque nextCursor to resume an in-progress
                                 id-pass. Absent ⇒ start a fresh pass.
              * ``pass_ts``    — ``_init_ts`` frozen at the start of a pass, kept
                                 across resumes so the pass sees one consistent
                                 snapshot upper bound.

            Per run we page by id from ``page_token`` (or the start), emitting rows
            where ``cursor < lastModifiedOn <= pass_ts``. ``max_records_per_batch``
            is a page-granular cap: once reached we stop at the page boundary and
            persist ``page_token`` = that page's nextCursor, leaving the committed
            watermark UNCHANGED (we haven't proven we've seen everything ≤ any given
            lastModifiedOn yet). When pagination is exhausted the pass is complete —
            we advance the committed watermark to ``pass_ts`` and clear
            ``page_token``/``pass_ts`` so the next run starts a fresh pass from the
            new floor. A run killed mid-pass (e.g. m2m token expiry) resumes from
            the last committed ``page_token`` instead of restarting.

            Progress within a pass is by id (the true sort key), so truncation never
            skips a record; the watermark only moves after a provably complete pass,
            so the next fresh pass's strict ``> committed`` filter can't skip an
            un-emitted record.
            """
            start_offset = start_offset or {}
            committed = self._as_cursor(start_offset.get("cursor"))
            page_token = start_offset.get("page_token") or ""
            # Freeze the snapshot boundary at pass start; keep it across resumes.
            pass_ts = start_offset.get("pass_ts")
            if not page_token or pass_ts is None:
                # Fresh pass.
                page_token = ""
                pass_ts = self._init_ts
            pass_ts = int(pass_ts)

            # Already caught up: committed floor has reached the snapshot boundary
            # and no pass is in flight — nothing new to emit, converge.
            if not page_token and committed is not None and committed >= pass_ts:
                return iter([]), {"cursor": committed}

            max_records = self._parse_max_records(table_options)
            url = f"{self.base_url}/assets"

            records: list[dict[str, Any]] = []
            next_page_token: str | None = None
            pass_complete = True
            for batch, next_cursor in cursor_paginate_pages(
                self._session, url, base_params, "assets", start_cursor=page_token
            ):
                for raw in batch:
                    cursor = self._as_cursor(raw.get("lastModifiedOn"))
                    # Incremental window: (committed, pass_ts].
                    if committed is not None and cursor is not None and cursor <= committed:
                        continue
                    if cursor is not None and cursor > pass_ts:
                        continue
                    records.append(self._shape_asset(raw))

                # Page-granular cap: stop at this boundary, resume here next run.
                # Only a page that has a real nextCursor can be a resume point; if
                # next_cursor is None this was the last page (pass completes).
                if (
                    max_records is not None
                    and len(records) >= max_records
                    and next_cursor is not None
                ):
                    next_page_token = next_cursor
                    pass_complete = False
                    break
            else:
                # Iterator exhausted without hitting the cap ⇒ pass complete.
                pass_complete = True

            if pass_complete:
                # Whole id-space scanned under one snapshot: safe to advance the
                # committed watermark to the snapshot boundary and clear pass state.
                new_committed = pass_ts if committed is None else max(committed, pass_ts)
                end_offset = {"cursor": new_committed}
            else:
                # Mid-pass: hold the watermark, persist the id resume point + the
                # frozen snapshot boundary.
                end_offset = {
                    "cursor": committed if committed is not None else 0,
                    "page_token": next_page_token,
                    "pass_ts": pass_ts,
                }

            return iter(records), end_offset

        # ------------------------------------------------------------------ #
        # Record shaping
        # ------------------------------------------------------------------ #

        def _shape_asset(self, raw: dict[str, Any]) -> dict[str, Any]:
            """Shape an asset record: normalize nested refs, stamp org.

            Used as the default transform for the ``assets`` table only;
            ``attributes`` / ``responsibilities`` / ``domains`` each pass their own
            explicit shaper.
            """
            rec = dict(raw)
            rec["domain"] = resource_ref(raw.get("domain"))
            rec["type"] = resource_ref(raw.get("type"))
            rec["status"] = resource_ref(raw.get("status"))
            rec["collibra_org"] = self.org
            return rec

        def _shape_attribute(self, raw: dict[str, Any]) -> dict[str, Any]:
            rec = dict(raw)
            rec["value"] = self._coerce_value_to_str(raw.get("value"))
            rec["type"] = resource_ref(raw.get("type"))
            rec["asset"] = resource_ref(raw.get("asset"))
            rec["collibra_org"] = self.org
            return rec

        def _shape_responsibility(self, raw: dict[str, Any]) -> dict[str, Any]:
            rec = dict(raw)
            rec["role"] = resource_ref(raw.get("role"))
            rec["baseResource"] = resource_ref(raw.get("baseResource"))
            rec["owner"] = resource_ref(raw.get("owner"))
            rec["collibra_org"] = self.org
            return rec

        def _shape_domain(self, raw: dict[str, Any]) -> dict[str, Any]:
            rec = dict(raw)
            rec["community"] = resource_ref(raw.get("community"))
            rec["type"] = resource_ref(raw.get("type"))
            rec["collibra_org"] = self.org
            return rec

        @staticmethod
        def _coerce_value_to_str(value: Any) -> str | None:
            """Coerce a polymorphic attribute ``value`` to a string.

            MultiValueListAttribute yields a list and other discriminators yield
            scalars; we JSON-encode non-string containers and stringify scalars so
            the raw value survives while the column stays a plain ``StringType``.
            The ``attributeDiscriminator`` field lets downstream jobs re-type it.
            """
            if value is None:
                return None
            if isinstance(value, str):
                return value
            if isinstance(value, (list, dict)):
                return json.dumps(value, ensure_ascii=False)
            if isinstance(value, bool):
                return "true" if value else "false"
            return str(value)

        # ------------------------------------------------------------------ #
        # Helpers
        # ------------------------------------------------------------------ #

        def _validate_table(self, table_name: str) -> None:
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(
                    f"Unsupported table {table_name!r}; "
                    f"supported: {SUPPORTED_TABLES}"
                )

        @staticmethod
        def _parse_max_records(table_options: dict[str, str]) -> int | None:
            """Parse ``max_records_per_batch`` (defaults to a bounded batch)."""
            raw = table_options.get("max_records_per_batch")
            if raw is None:
                return DEFAULT_MAX_RECORDS_PER_BATCH
            try:
                value = int(raw)
            except (TypeError, ValueError):
                return DEFAULT_MAX_RECORDS_PER_BATCH
            return value if value > 0 else None

        @staticmethod
        def _as_cursor(value: Any) -> int | None:
            """Coerce a ``lastModifiedOn`` value to a comparable int.

            Real Collibra returns int64 epoch ms; numeric strings are tolerated.
            Non-numeric values (e.g. absent cursors) return ``None`` and are
            treated as uncomparable so they never break ordering.
            """
            if isinstance(value, bool):
                return None
            if isinstance(value, int):
                return value
            if isinstance(value, float):
                return int(value)
            if isinstance(value, str):
                try:
                    return int(value)
                except ValueError:
                    return None
            return None


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = CollibraLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
