# pylint: disable=too-many-lines
from typing import Any, Dict

TABLE_CONFIG: Dict[str, Dict[str, Any]] = {
    "Advance": {
        "entity_set": "Advance",
        "primary_keys": ["NonRecurringPayment_externalCode", "externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "AdvancesAccumulation": {
        "entity_set": "AdvancesAccumulation",
        "primary_keys": ["externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "AdvancesEligibility": {
        "entity_set": "AdvancesEligibility",
        "primary_keys": ["effectiveStartDate", "externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "AdvancesInstallments": {
        "entity_set": "AdvancesInstallments",
        "primary_keys": [
            "Advance_externalCode",
            "NonRecurringPayment_externalCode",
            "externalCode"
        ],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "AssignedComplianceForm": {
        "entity_set": "AssignedComplianceForm",
        "primary_keys": ["id"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "Attachment": {
        "entity_set": "Attachment",
        "primary_keys": ["attachmentId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "Bank": {
        "entity_set": "Bank",
        "primary_keys": ["externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "Benefit": {
        "entity_set": "Benefit",
        "primary_keys": ["benefitId", "effectiveStartDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "BudgetGroup": {
        "entity_set": "BudgetGroup",
        "primary_keys": ["externalCode", "effectiveStartDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "CalibrationSession": {
        "entity_set": "CalibrationSession",
        "primary_keys": ["sessionId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "CalibrationSessionSubject": {
        "entity_set": "CalibrationSessionSubject",
        "primary_keys": ["sessionSubjectId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "CalibrationSubjectRank": {
        "entity_set": "CalibrationSubjectRank",
        "primary_keys": ["subjectRankId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "CalibrationTemplate": {
        "entity_set": "CalibrationTemplate",
        "primary_keys": ["templateId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "Candidate": {
        "entity_set": "Candidate",
        "primary_keys": ["candidateId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "CandidateBackground_Certificates": {
        "entity_set": "CandidateBackground_Certificates",
        "primary_keys": ["backgroundElementId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "CandidateBackground_Education": {
        "entity_set": "CandidateBackground_Education",
        "primary_keys": ["backgroundElementId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "CandidateBackground_InsideWorkExperience": {
        "entity_set": "CandidateBackground_InsideWorkExperience",
        "primary_keys": ["backgroundElementId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "CandidateBackground_Languages": {
        "entity_set": "CandidateBackground_Languages",
        "primary_keys": ["backgroundElementId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "CandidateBackground_OutsideWorkExperience": {
        "entity_set": "CandidateBackground_OutsideWorkExperience",
        "primary_keys": ["backgroundElementId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "CandidateBackground_TalentPool": {
        "entity_set": "CandidateBackground_TalentPool",
        "primary_keys": ["backgroundElementId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "CandidateBackground_TalentPoolcorp": {
        "entity_set": "CandidateBackground_TalentPoolcorp",
        "primary_keys": ["backgroundElementId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "CandidateComments": {
        "entity_set": "CandidateComments",
        "primary_keys": ["commentId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "CandidateLight": {
        "entity_set": "CandidateLight",
        "primary_keys": ["candidateId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "CompetencyEntity": {
        "entity_set": "CompetencyEntity",
        "primary_keys": ["externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "ComplianceDocumentFlow": {
        "entity_set": "ComplianceDocumentFlow",
        "primary_keys": ["documentFlowCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "ComplianceFormData": {
        "entity_set": "ComplianceFormData",
        "primary_keys": ["externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "ComplianceFormSignature": {
        "entity_set": "ComplianceFormSignature",
        "primary_keys": ["ComplianceFormData_externalCode", "externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "ComplianceProcess": {
        "entity_set": "ComplianceProcess",
        "primary_keys": ["processId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "ComplianceProcessTask": {
        "entity_set": "ComplianceProcessTask",
        "primary_keys": ["taskId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "Country": {
        "entity_set": "Country",
        "primary_keys": ["code", "effectiveStartDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "CurrencyConversion": {
        "entity_set": "CurrencyConversion",
        "primary_keys": ["code", "effectiveStartDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "CustomPayType": {
        "entity_set": "CustomPayType",
        "primary_keys": ["externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "CustomPayTypeAssignment": {
        "entity_set": "CustomPayTypeAssignment",
        "primary_keys": ["externalCode", "CustomPayType_externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "DGExpression": {
        "entity_set": "DGExpression",
        "primary_keys": ["expressionID"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "DGField": {
        "entity_set": "DGField",
        "primary_keys": ["name"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "DGFieldOperator": {
        "entity_set": "DGFieldOperator",
        "primary_keys": ["token"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "DGFieldValue": {
        "entity_set": "DGFieldValue",
        "primary_keys": ["fieldValue"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "DGFilter": {
        "entity_set": "DGFilter",
        "primary_keys": ["filterId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "DGPeoplePool": {
        "entity_set": "DGPeoplePool",
        "primary_keys": ["peoplePoolId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "DeductionScreenId": {
        "entity_set": "DeductionScreenId",
        "primary_keys": ["externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "DevLearningCertifications": {
        "entity_set": "DevLearningCertifications",
        "primary_keys": ["certificateId", "learningId"],
        "cursor_field": "certificateLastModifiedDate",
        "ingestion_type": "cdc",
    },
    "DevLearning_4201": {
        "entity_set": "DevLearning_4201",
        "primary_keys": ["learningId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "DynamicGroup": {
        "entity_set": "DynamicGroup",
        "primary_keys": ["groupID"],
        "cursor_field": "lastModifiedDate",
        "ingestion_type": "cdc",
    },
    "DynamicGroupDefinition": {
        "entity_set": "DynamicGroupDefinition",
        "primary_keys": ["groupID"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "EMEvent": {
        "entity_set": "EMEvent",
        "primary_keys": ["id"],
        "cursor_field": "eventTime",
        "ingestion_type": "cdc",
    },
    "EMEventAttribute": {
        "entity_set": "EMEventAttribute",
        "primary_keys": ["id"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "EMEventPayload": {
        "entity_set": "EMEventPayload",
        "primary_keys": ["id"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "EMMonitoredProcess": {
        "entity_set": "EMMonitoredProcess",
        "primary_keys": ["processDefinitionId", "processInstanceId", "processType"],
        "cursor_field": "lastEventTime",
        "ingestion_type": "cdc",
    },
    "EmpBeneficiary": {
        "entity_set": "EmpBeneficiary",
        "primary_keys": ["userId", "personIdExternal"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "EmpCompensation": {
        "entity_set": "EmpCompensation",
        "primary_keys": ["startDate", "userId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "EmpCompensationCalculated": {
        "entity_set": "EmpCompensationCalculated",
        "primary_keys": ["seqNumber", "startDate", "userId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "EmpCompensationGroupSumCalculated": {
        "entity_set": "EmpCompensationGroupSumCalculated",
        "primary_keys": ["seqNumber", "startDate", "userId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "EmpCostAssignment": {
        "entity_set": "EmpCostAssignment",
        "primary_keys": ["effectiveStartDate", "worker"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "EmpEmployment": {
        "entity_set": "EmpEmployment",
        "primary_keys": ["prevEmployeeId", "userId", "personIdExternal"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "EmpEmploymentHigherDuty": {
        "entity_set": "EmpEmploymentHigherDuty",
        "primary_keys": ["personIdExternal", "userId", "homeAssignment", "startDate"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "EmpEmploymentTermination": {
        "entity_set": "EmpEmploymentTermination",
        "primary_keys": ["userId", "attachmentId", "personIdExternal", "newMainEmploymentId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "EmpJob": {
        "entity_set": "EmpJob",
        "primary_keys": ["userId", "managerId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "EmpJobRelationships": {
        "entity_set": "EmpJobRelationships",
        "primary_keys": ["relUserId", "userId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "EmpPayCompNonRecurring": {
        "entity_set": "EmpPayCompNonRecurring",
        "primary_keys": ["payComponentCode", "payDate", "userId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "EmpPayCompRecurring": {
        "entity_set": "EmpPayCompRecurring",
        "primary_keys": ["seqNumber", "startDate", "userId", "payComponent"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "EmpPensionPayout": {
        "entity_set": "EmpPensionPayout",
        "primary_keys": ["userId", "personIdExternal"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "EmpWorkPermit": {
        "entity_set": "EmpWorkPermit",
        "primary_keys": ["attachmentId", "userId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "EmployeeCompensation": {
        "entity_set": "employeeCompensations",
        "primary_keys": ["compEntryId", "compPlanId", "formDataId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "EmployeeDismissalProtection": {
        "entity_set": "EmployeeDismissalProtection",
        "primary_keys": ["workerId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "EmployeeDismissalProtectionDetail": {
        "entity_set": "EmployeeDismissalProtectionDetail",
        "primary_keys": ["EmployeeDismissalProtection_workerId", "externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "EmployeePayrollRunResults": {
        "entity_set": "EmployeePayrollRunResults",
        "primary_keys": ["externalCode", "mdfSystemEffectiveStartDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "EmployeePayrollRunResultsItems": {
        "entity_set": "EmployeePayrollRunResultsItems",
        "primary_keys": [
            "EmployeePayrollRunResults_externalCode",
            "EmployeePayrollRunResults_mdfSystemEffectiveStartDate",
            "externalCode"
        ],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "ExternalUser": {
        "entity_set": "ExternalUser",
        "primary_keys": ["userId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOBusinessUnit": {
        "entity_set": "FOBusinessUnit",
        "primary_keys": ["externalCode", "startDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOCompany": {
        "entity_set": "FOCompany",
        "primary_keys": ["externalCode", "startDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOCorporateAddressDEFLT": {
        "entity_set": "FOCorporateAddressDEFLT",
        "primary_keys": ["addressId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOCostCenter": {
        "entity_set": "FOCostCenter",
        "primary_keys": ["externalCode", "startDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FODepartment": {
        "entity_set": "FODepartment",
        "primary_keys": ["externalCode", "startDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FODivision": {
        "entity_set": "FODivision",
        "primary_keys": ["externalCode", "startDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FODynamicRole": {
        "entity_set": "FODynamicRole",
        "primary_keys": ["dynamicRoleAssignmentId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOEventReason": {
        "entity_set": "FOEventReason",
        "primary_keys": ["externalCode", "startDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOFrequency": {
        "entity_set": "FOFrequency",
        "primary_keys": ["externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOGeozone": {
        "entity_set": "FOGeozone",
        "primary_keys": ["externalCode", "startDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOJobClassLocalAUS": {
        "entity_set": "FOJobClassLocalAUS",
        "primary_keys": ["externalCode", "startDate", "country"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOJobClassLocalBRA": {
        "entity_set": "FOJobClassLocalBRA",
        "primary_keys": ["externalCode", "startDate", "country"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOJobClassLocalCAN": {
        "entity_set": "FOJobClassLocalCAN",
        "primary_keys": ["externalCode", "startDate", "country"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOJobClassLocalDEFLT": {
        "entity_set": "FOJobClassLocalDEFLT",
        "primary_keys": ["externalCode", "startDate", "country"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOJobClassLocalFRA": {
        "entity_set": "FOJobClassLocalFRA",
        "primary_keys": ["externalCode", "startDate", "country"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOJobClassLocalGBR": {
        "entity_set": "FOJobClassLocalGBR",
        "primary_keys": ["externalCode", "startDate", "country"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOJobClassLocalITA": {
        "entity_set": "FOJobClassLocalITA",
        "primary_keys": ["externalCode", "startDate", "country"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOJobClassLocalUSA": {
        "entity_set": "FOJobClassLocalUSA",
        "primary_keys": ["externalCode", "startDate", "country"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOJobCode": {
        "entity_set": "FOJobCode",
        "primary_keys": ["externalCode", "startDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOJobFunction": {
        "entity_set": "FOJobFunction",
        "primary_keys": ["externalCode", "startDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOLocation": {
        "entity_set": "FOLocation",
        "primary_keys": ["externalCode", "startDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOLocationGroup": {
        "entity_set": "FOLocationGroup",
        "primary_keys": ["externalCode", "startDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOPayComponent": {
        "entity_set": "FOPayComponent",
        "primary_keys": ["externalCode", "startDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOPayComponentGroup": {
        "entity_set": "FOPayComponentGroup",
        "primary_keys": ["externalCode", "startDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOPayGrade": {
        "entity_set": "FOPayGrade",
        "primary_keys": ["externalCode", "startDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOPayGroup": {
        "entity_set": "FOPayGroup",
        "primary_keys": ["externalCode", "startDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "FOPayRange": {
        "entity_set": "FOPayRange",
        "primary_keys": ["externalCode", "startDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "HireDateChange": {
        "entity_set": "HireDateChange",
        "primary_keys": ["usersSysId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "InterviewIndividualAssessment": {
        "entity_set": "InterviewIndividualAssessment",
        "primary_keys": ["interviewIndividualAssessmentId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "InterviewOverallAssessment": {
        "entity_set": "InterviewOverallAssessment",
        "primary_keys": ["interviewOverallAssessmentId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobApplication": {
        "entity_set": "JobApplication",
        "primary_keys": ["applicationId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "JobApplicationAssessmentOrder": {
        "entity_set": "JobApplicationAssessmentOrder",
        "primary_keys": ["id"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "JobApplicationAssessmentReport": {
        "entity_set": "JobApplicationAssessmentReport",
        "primary_keys": ["id"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobApplicationAssessmentReportDetail": {
        "entity_set": "JobApplicationAssessmentReportDetail",
        "primary_keys": ["id"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobApplicationAudit": {
        "entity_set": "JobApplicationAudit",
        "primary_keys": ["fieldOrderPos", "revNumber"],
        "cursor_field": "lastModifiedDate",
        "ingestion_type": "cdc",
    },
    "JobApplicationBackgroundCheckRequest": {
        "entity_set": "JobApplicationBackgroundCheckRequest",
        "primary_keys": ["requestId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "JobApplicationBackgroundCheckResult": {
        "entity_set": "JobApplicationBackgroundCheckResult",
        "primary_keys": ["statusId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobApplicationComments": {
        "entity_set": "JobApplicationComments",
        "primary_keys": ["commentId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobApplicationInterview": {
        "entity_set": "JobApplicationInterview",
        "primary_keys": ["applicationInterviewId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobApplicationOnboardingData": {
        "entity_set": "JobApplicationOnboardingData",
        "primary_keys": ["onboardingId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobApplicationOnboardingStatus": {
        "entity_set": "JobApplicationOnboardingStatus",
        "primary_keys": ["onboardingStatusId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobApplicationQuestionResponse": {
        "entity_set": "JobApplicationQuestionResponse",
        "primary_keys": ["applicationId", "order"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobApplicationSnapshot_Certificates": {
        "entity_set": "JobApplicationSnapshot_Certificates",
        "primary_keys": ["applicationId", "backgroundElementId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "JobApplicationSnapshot_Education": {
        "entity_set": "JobApplicationSnapshot_Education",
        "primary_keys": ["applicationId", "backgroundElementId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "JobApplicationSnapshot_InsideWorkExperience": {
        "entity_set": "JobApplicationSnapshot_InsideWorkExperience",
        "primary_keys": ["applicationId", "backgroundElementId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "JobApplicationSnapshot_Languages": {
        "entity_set": "JobApplicationSnapshot_Languages",
        "primary_keys": ["applicationId", "backgroundElementId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "JobApplicationSnapshot_OutsideWorkExperience": {
        "entity_set": "JobApplicationSnapshot_OutsideWorkExperience",
        "primary_keys": ["applicationId", "backgroundElementId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "JobApplicationSnapshot_TalentPool": {
        "entity_set": "JobApplicationSnapshot_TalentPool",
        "primary_keys": ["applicationId", "backgroundElementId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "JobApplicationSnapshot_TalentPoolcorp": {
        "entity_set": "JobApplicationSnapshot_TalentPoolcorp",
        "primary_keys": ["applicationId", "backgroundElementId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "JobApplicationStatus": {
        "entity_set": "JobApplicationStatus",
        "primary_keys": ["appStatusSetId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobApplicationStatusAuditTrail": {
        "entity_set": "JobApplicationStatusAuditTrail",
        "primary_keys": ["revNumber"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "JobApplicationStatusLabel": {
        "entity_set": "JobApplicationStatusLabel",
        "primary_keys": ["appStatusId", "locale"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobOffer": {
        "entity_set": "JobOffer",
        "primary_keys": ["offerApprovalId"],
        "cursor_field": "lastModifiedDate",
        "ingestion_type": "cdc",
    },
    "JobOfferApprover": {
        "entity_set": "JobOfferApprover",
        "primary_keys": ["offerApproverId"],
        "cursor_field": "lastModifiedDate",
        "ingestion_type": "cdc",
    },
    "JobReqFwdCandidates": {
        "entity_set": "JobReqFwdCandidates",
        "primary_keys": ["candidateId", "jobReqId"],
        "cursor_field": "lastModifiedDate",
        "ingestion_type": "cdc",
    },
    "JobReqQuestion": {
        "entity_set": "JobReqQuestion",
        "primary_keys": ["questionId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobReqScreeningQuestion": {
        "entity_set": "JobReqScreeningQuestion",
        "primary_keys": ["jobReqId", "locale", "order"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobReqScreeningQuestionChoice": {
        "entity_set": "JobReqScreeningQuestionChoice",
        "primary_keys": ["locale", "optionId", "optionValue"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobRequisition": {
        "entity_set": "JobRequisition",
        "primary_keys": ["jobReqId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "JobRequisitionGroupOperator": {
        "entity_set": "JobRequisitionGroupOperator",
        "primary_keys": ["jobReqId", "operatorRole", "userGroupId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobRequisitionLocale": {
        "entity_set": "JobRequisitionLocale",
        "primary_keys": ["jobReqLocalId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobRequisitionOperator": {
        "entity_set": "JobRequisitionOperator",
        "primary_keys": ["jobReqId", "operatorRole", "userName"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "JobRequisitionPosting": {
        "entity_set": "JobRequisitionPosting",
        "primary_keys": ["jobPostingId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "JourneyDetails": {
        "entity_set": "journeys",
        "primary_keys": ["journeyId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "LegacyPositionEntity": {
        "entity_set": "LegacyPositionEntity",
        "primary_keys": ["positionId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "LocalizedData": {
        "entity_set": "LocalizedData",
        "primary_keys": ["localizedDataCode", "localizedDataLocale"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "MDFEnumValue": {
        "entity_set": "MDFEnumValue",
        "primary_keys": ["key"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "MDFLocalizedValue": {
        "entity_set": "MDFLocalizedValue",
        "primary_keys": ["locale"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "NominationTarget": {
        "entity_set": "NominationTarget",
        "primary_keys": ["nominationId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "NomineeHistory": {
        "entity_set": "NomineeHistory",
        "primary_keys": ["id"],
        "cursor_field": "modifiedDateTime",
        "ingestion_type": "cdc",
    },
    "ONB2EquipmentActivity": {
        "entity_set": "ONB2EquipmentActivity",
        "primary_keys": ["activityId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "ONB2EquipmentType": {
        "entity_set": "ONB2EquipmentType",
        "primary_keys": ["code"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "ONB2EquipmentTypeValue": {
        "entity_set": "ONB2EquipmentTypeValue",
        "primary_keys": ["code"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "ONB2Process": {
        "entity_set": "ONB2Process",
        "primary_keys": ["processId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "ONB2ProcessTask": {
        "entity_set": "ONB2ProcessTask",
        "primary_keys": ["ONB2Process_processId", "taskId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "ONB2ProcessTrigger": {
        "entity_set": "ONB2ProcessTrigger",
        "primary_keys": ["triggerId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "OfferLetter": {
        "entity_set": "OfferLetter",
        "primary_keys": ["offerLetterId"],
        "cursor_field": "lastModifiedDate",
        "ingestion_type": "cdc",
    },
    "OnboardingCandidateInfo": {
        "entity_set": "OnboardingCandidateInfo",
        "primary_keys": ["applicantId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "OnboardingEquipment": {
        "entity_set": "OnboardingEquipment",
        "primary_keys": [
            "OnboardingEquipmentActivity_activityId",
            "OnboardingNewHireActivitiesStep_processStepId",
            "OnboardingProcess_onboardingProcessId",
            "equipmentId"
        ],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "OnboardingEquipmentActivity": {
        "entity_set": "OnboardingEquipmentActivity",
        "primary_keys": [
            "OnboardingNewHireActivitiesStep_processStepId",
            "OnboardingProcess_onboardingProcessId",
            "activityId"
        ],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "OnboardingEquipmentType": {
        "entity_set": "OnboardingEquipmentType",
        "primary_keys": ["code"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "OnboardingEquipmentTypeValue": {
        "entity_set": "OnboardingEquipmentTypeValue",
        "primary_keys": ["code"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "OnboardingGoal": {
        "entity_set": "OnboardingGoal",
        "primary_keys": [
            "OnboardingGoalActivity_activityId",
            "OnboardingGoalCategory_externalCode",
            "OnboardingNewHireActivitiesStep_processStepId",
            "OnboardingProcess_onboardingProcessId",
            "goalId"
        ],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "OnboardingGoalActivity": {
        "entity_set": "OnboardingGoalActivity",
        "primary_keys": [
            "OnboardingNewHireActivitiesStep_processStepId",
            "OnboardingProcess_onboardingProcessId",
            "activityId"
        ],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "OnboardingGoalCategory": {
        "entity_set": "OnboardingGoalCategory",
        "primary_keys": [
            "OnboardingGoalActivity_activityId",
            "OnboardingNewHireActivitiesStep_processStepId",
            "OnboardingProcess_onboardingProcessId",
            "externalCode"
        ],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "OnboardingMeetingActivity": {
        "entity_set": "OnboardingMeetingActivity",
        "primary_keys": [
            "OnboardingNewHireActivitiesStep_processStepId",
            "OnboardingProcess_onboardingProcessId",
            "activityId"
        ],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "OnboardingMeetingEvent": {
        "entity_set": "OnboardingMeetingEvent",
        "primary_keys": [
            "OnboardingMeetingActivity_activityId",
            "OnboardingNewHireActivitiesStep_processStepId",
            "OnboardingProcess_onboardingProcessId",
            "externalCode"
        ],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "OnboardingNewHireActivitiesStep": {
        "entity_set": "OnboardingNewHireActivitiesStep",
        "primary_keys": ["OnboardingProcess_onboardingProcessId", "processStepId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "OnboardingProcess": {
        "entity_set": "OnboardingProcess",
        "primary_keys": ["onboardingProcessId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "OneTimeDeduction": {
        "entity_set": "OneTimeDeduction",
        "primary_keys": ["externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "PaymentInformationDetailV3": {
        "entity_set": "PaymentInformationDetailV3",
        "primary_keys": [
            "externalCode",
            "PaymentInformationV3_worker",
            "PaymentInformationV3_effectiveStartDate"
        ],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "PaymentInformationDetailV3USA": {
        "entity_set": "PaymentInformationDetailV3USA",
        "primary_keys": [
            "externalCode",
            "PaymentInformationV3_worker",
            "PaymentInformationV3_effectiveStartDate",
            "PaymentInformationDetailV3_externalCode"
        ],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "PaymentInformationV3": {
        "entity_set": "PaymentInformationV3",
        "primary_keys": ["worker", "effectiveStartDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "PaymentMethodAssignmentV3": {
        "entity_set": "PaymentMethodAssignmentV3",
        "primary_keys": ["externalCode", "PaymentMethodV3_externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "PaymentMethodV3": {
        "entity_set": "PaymentMethodV3",
        "primary_keys": ["externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "PersonEmpTerminationInfo": {
        "entity_set": "PersonEmpTerminationInfo",
        "primary_keys": ["personIdExternal"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "Photo": {
        "entity_set": "Photo",
        "primary_keys": ["photoId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "PickListV2": {
        "entity_set": "PickListV2",
        "primary_keys": ["effectiveStartDate", "id"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "PickListValueV2": {
        "entity_set": "PickListValueV2",
        "primary_keys": ["PickListV2_effectiveStartDate", "PickListV2_id", "externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "PicklistOption": {
        "entity_set": "PicklistOption",
        "primary_keys": ["id", "externalCode", "optionValue", "sortOrder", "status"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "RBPBasicPermission": {
        "entity_set": "RBPBasicPermission",
        "primary_keys": ["permissionId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "RBPRole": {
        "entity_set": "RBPRole",
        "primary_keys": ["roleId"],
        "cursor_field": "lastModifiedDate",
        "ingestion_type": "cdc",
    },
    "RBPRule": {
        "entity_set": "RBPRule",
        "primary_keys": ["ruleId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "RCMAdminReassignOfferApprover": {
        "entity_set": "RCMAdminReassignOfferApprover",
        "primary_keys": ["applicationId", "currUserId", "offerDetailId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "RcmCompetency": {
        "entity_set": "RcmCompetency",
        "primary_keys": ["rcmCompetencyId", "locale"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "RecurringDeduction": {
        "entity_set": "RecurringDeduction",
        "primary_keys": ["effectiveStartDate", "userSysId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "RecurringDeductionItem": {
        "entity_set": "RecurringDeductionItem",
        "primary_keys": [
            "RecurringDeduction_effectiveStartDate",
            "RecurringDeduction_userSysId",
            "payComponentType"
        ],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "ScimGroup": {
        "entity_set": "Groups",
        "primary_keys": ["id"],
        "cursor_field": "meta_lastModified",
        "ingestion_type": "cdc",
    },
    "ScimUser": {
        "entity_set": "Users",
        "primary_keys": ["id"],
        "cursor_field": "meta_lastModified",
        "ingestion_type": "cdc",
    },
    "Successor": {
        "entity_set": "Successor",
        "primary_keys": ["id"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "TalentGraphicOption": {
        "entity_set": "TalentGraphicOption",
        "primary_keys": ["dataIndex", "optionKey"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "TalentPool": {
        "entity_set": "TalentPool",
        "primary_keys": ["code", "effectiveStartDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "TalentRatings": {
        "entity_set": "TalentRatings",
        "primary_keys": [
            "feedbackId",
            "feedbackModule",
            "formDataId",
            "formContentId",
            "feedbackType",
            "feedbackSource",
            "feedbackScaleId",
            "employeeId"
        ],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "Territory": {
        "entity_set": "Territory",
        "primary_keys": ["territoryCode"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "User": {
        "entity_set": "User",
        "primary_keys": ["userId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "UserPermissions": {
        "entity_set": "UserPermissions",
        "primary_keys": ["userId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "achievement": {
        "entity_set": "Achievement",
        "primary_keys": ["achievementId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "activity": {
        "entity_set": "Activity",
        "primary_keys": ["activityId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "budget_period": {
        "entity_set": "BudgetPeriodGO",
        "primary_keys": ["budgetPeriodId", "effectiveStartDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "calibration_competency_rating": {
        "entity_set": "CalibrationCompetencyRating",
        "primary_keys": ["competencyId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "calibration_executive_reviewer": {
        "entity_set": "CalibrationExecutiveReviewer",
        "primary_keys": ["id"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "calibration_rating": {
        "entity_set": "CalibrationRating",
        "primary_keys": ["ratingType"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "calibration_rating_option": {
        "entity_set": "CalibrationRatingOption",
        "primary_keys": ["value"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "calibration_session": {
        "entity_set": "CalibrationSession",
        "primary_keys": ["id"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "calibration_session_reviewer": {
        "entity_set": "CalibrationSessionReviewer",
        "primary_keys": ["sessionReviewerId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "calibration_subject": {
        "entity_set": "CalibrationSubject",
        "primary_keys": ["id"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "calibration_subject_comment": {
        "entity_set": "CalibrationSubjectComment",
        "primary_keys": ["id"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "clock_in_clock_out_groups": {
        "entity_set": "ClockInClockOutGroups",
        "primary_keys": ["code"],
        "cursor_field": "lastChangedAt",
        "ingestion_type": "cdc",
    },
    "continuous_performance_user_permission": {
        "entity_set": "ContinuousPerformanceUserPermission",
        "primary_keys": ["permType", "targetUserId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "cpm_achievements": {
        "entity_set": "achievements",
        "primary_keys": ["achievementRecordId", "activityRecordId"],
        "cursor_field": "lastModifiedDate",
        "ingestion_type": "cdc",
    },
    "cpm_activities": {
        "entity_set": "activities",
        "primary_keys": ["activityRecordId"],
        "cursor_field": "lastModifiedDate",
        "ingestion_type": "cdc",
    },
    "cpm_activity_status": {
        "entity_set": "activityStatuses",
        "primary_keys": ["activityStatusRecordId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "cpm_activity_updates": {
        "entity_set": "activityUpdates",
        "primary_keys": ["activityUpdateRecordId"],
        "cursor_field": "lastModifiedDate",
        "ingestion_type": "cdc",
    },
    "cpm_user_permissions": {
        "entity_set": "userPermissions",
        "primary_keys": ["targetUserAssignmentUUID"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "cust_CommutingAllowance": {
        "entity_set": "cust_CommutingAllowance",
        "primary_keys": ["effectiveStartDate", "externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "cust_ProgressiveDisciplinaryAction": {
        "entity_set": "cust_ProgressiveDisciplinaryAction",
        "primary_keys": ["effectiveStartDate", "externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "cust_auth_sign": {
        "entity_set": "cust_auth_sign",
        "primary_keys": ["externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "cust_grievances": {
        "entity_set": "cust_grievances",
        "primary_keys": ["effectiveStartDate", "externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "cust_voluntarySeparationRequest": {
        "entity_set": "cust_voluntarySeparationRequest",
        "primary_keys": ["effectiveStartDate", "externalCode"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "custom_nav": {
        "entity_set": "CustomNav",
        "primary_keys": ["title"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "custom_tasks": {
        "entity_set": "customTasks",
        "primary_keys": ["id"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "extension_point_task": {
        "entity_set": "ExtensionPointTaskDetail",
        "primary_keys": ["processId", "taskId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "feedback": {
        "entity_set": "feedback",
        "primary_keys": ["recordId"],
        "cursor_field": "lastModifiedAt",
        "ingestion_type": "cdc",
    },
    "feedback_requests": {
        "entity_set": "feedbackRequests",
        "primary_keys": ["recordId"],
        "cursor_field": "lastModifiedAt",
        "ingestion_type": "cdc",
    },
    "form360_participant_detail": {
        "entity_set": "Form360ParticipantDetail",
        "primary_keys": ["formContentId", "formDataId", "participantId", "columnKey"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "form_competency": {
        "entity_set": "FormCompetency",
        "primary_keys": ["formContentId", "formDataId", "itemId", "sectionIndex"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "form_customized_weighted_rating_section": {
        "entity_set": "FormCustomizedWeightedRatingSection",
        "primary_keys": ["formContentId", "formDataId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "form_folder": {
        "entity_set": "FormFolder",
        "primary_keys": ["folderId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "form_header": {
        "entity_set": "FormHeader",
        "primary_keys": ["formDataId"],
        "cursor_field": "formLastModifiedDate",
        "ingestion_type": "cdc",
    },
    "form_objective": {
        "entity_set": "FormObjective",
        "primary_keys": ["formContentId", "formDataId", "itemId", "sectionIndex"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "form_perf_pot_summary_section": {
        "entity_set": "FormPerfPotSummarySection",
        "primary_keys": ["formContentId", "formDataId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "form_review_feedback": {
        "entity_set": "FormReviewFeedback",
        "primary_keys": ["feedbackId"],
        "cursor_field": "responseDate",
        "ingestion_type": "cdc",
    },
    "form_template": {
        "entity_set": "FormTemplate",
        "primary_keys": ["formTemplateId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "functional_area": {
        "entity_set": "FunctionalAreaGO",
        "primary_keys": ["functionalAreaID", "effectiveStartDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "fund": {
        "entity_set": "FundGO",
        "primary_keys": ["externalCode", "effectiveStartDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "fund_center": {
        "entity_set": "FundCenterGO",
        "primary_keys": ["externalCode", "effectiveStartDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "goal_1": {
        "entity_set": "Goal_1",
        "primary_keys": ["id"],
        "cursor_field": "lastModified",
        "ingestion_type": "cdc",
    },
    "goal_comment_1": {
        "entity_set": "GoalComment_1",
        "primary_keys": ["id"],
        "cursor_field": "lastModified",
        "ingestion_type": "cdc",
    },
    "goal_permission_1": {
        "entity_set": "GoalPermission_1",
        "primary_keys": ["id"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "goal_plan_state": {
        "entity_set": "GoalPlanState",
        "primary_keys": ["planId", "stateId", "userId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "goal_plan_template": {
        "entity_set": "GoalPlanTemplate",
        "primary_keys": ["id"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "goal_task_1": {
        "entity_set": "GoalTask_1",
        "primary_keys": ["id"],
        "cursor_field": "lastModified",
        "ingestion_type": "cdc",
    },
    "goal_weight": {
        "entity_set": "GoalWeight",
        "primary_keys": ["planId", "type"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "grant": {
        "entity_set": "GrantGO",
        "primary_keys": ["grantCode", "effectiveStartDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "i9_audit_trail_record": {
        "entity_set": "i9AuditTrailRecords",
        "primary_keys": ["externalCode"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "pbc_employee_financing": {
        "entity_set": "employeeFinancingData",
        "primary_keys": ["id", "objectType", "startDate", "endDate"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "pbc_employee_grouping": {
        "entity_set": "employeeGroupings",
        "primary_keys": ["id"],
        "cursor_field": "lastModifiedTimestamp",
        "ingestion_type": "cdc",
    },
    "pbc_symbolic_account": {
        "entity_set": "symbolicAccounts",
        "primary_keys": ["id"],
        "cursor_field": "lastModifiedTimestamp",
        "ingestion_type": "cdc",
    },
    "project_controlling_object": {
        "entity_set": "ProjectControllingObject",
        "primary_keys": ["externalCode", "effectiveStartDate"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "review_route_map": {
        "entity_set": "reviewRouteMaps",
        "primary_keys": ["reviewId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "scim_group": {
        "entity_set": "Groups",
        "primary_keys": ["id"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "scim_user": {
        "entity_set": "Users",
        "primary_keys": ["id"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "success_store_content": {
        "entity_set": "SuccessStoreContent",
        "primary_keys": ["contentId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "success_store_content_blob": {
        "entity_set": "SuccessStoreContentBlob",
        "primary_keys": ["contentId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "supporter_feedback": {
        "entity_set": "SupporterFeedback",
        "primary_keys": ["feedbackId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "theme_config": {
        "entity_set": "ThemeConfig",
        "primary_keys": ["id"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "theme_info": {
        "entity_set": "ThemeInfo",
        "primary_keys": ["id"],
        "cursor_field": "lastModifiedDate",
        "ingestion_type": "cdc",
    },
    "theme_template": {
        "entity_set": "ThemeTemplate",
        "primary_keys": ["id"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "time_event_types": {
        "entity_set": "TimeEventTypes",
        "primary_keys": ["code"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "todo": {
        "entity_set": "Todo",
        "primary_keys": ["categoryId"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
    "todo_entry_v2": {
        "entity_set": "TodoEntryV2",
        "primary_keys": ["todoEntryId"],
        "cursor_field": "lastModifiedDateTime",
        "ingestion_type": "cdc",
    },
    "user_capabilities": {
        "entity_set": "userCapabilities",
        "primary_keys": ["targetUserAssignmentUUID"],
        "cursor_field": None,
        "ingestion_type": "snapshot",
    },
}

DEDUPE_TABLES = {"PicklistOption", "TalentRatings"}
