# ==============================================================================
# Merged Lakeflow Source: microsoft_purview
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import logging
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/microsoft_purview/microsoft_purview_schemas.py
    ########################################################

    SYSTEM_DATA_STRUCT = StructType(
        [
            StructField("createdAt", StringType(), True),
            StructField("createdBy", StringType(), True),
            StructField("lastModifiedAt", StringType(), True),
            StructField("lastModifiedBy", StringType(), True),
            StructField("expiredAt", StringType(), True),
            StructField("expiredBy", StringType(), True),
            StructField("provisioningState", StringType(), True),
        ]
    )

    # CatalogModelContactsValueInner — one contact assignment.
    CONTACT_STRUCT = StructType(
        [
            StructField("id", StringType(), True),
            StructField("description", StringType(), True),
        ]
    )

    # ContactsMap — contacts keyed by role. Kept as an explicit struct (not a map)
    # so each role is a first-class, typed array.
    CONTACTS_STRUCT = StructType(
        [
            StructField("owner", ArrayType(CONTACT_STRUCT), True),
            StructField("expert", ArrayType(CONTACT_STRUCT), True),
            StructField("databaseAdmin", ArrayType(CONTACT_STRUCT), True),
        ]
    )

    # CatalogModelExternalLink — used by data product termsOfUse / documentation.
    EXTERNAL_LINK_STRUCT = StructType(
        [
            StructField("url", StringType(), True),
            StructField("name", StringType(), True),
            StructField("dataAssetId", StringType(), True),
        ]
    )

    # CatalogModelManagedAttribute — governance custom attribute on any entity.
    MANAGED_ATTRIBUTE_STRUCT = StructType(
        [
            StructField("name", StringType(), True),
            StructField("value", StringType(), True),
            StructField("isRequired", BooleanType(), True),
        ]
    )

    # CatalogModelTermResource — external resource link on a term.
    TERM_RESOURCE_STRUCT = StructType(
        [
            StructField("name", StringType(), True),
            StructField("url", StringType(), True),
        ]
    )

    # CatalogModelDataProductAllOfAdditionalProperties.
    ADDITIONAL_PROPERTIES_STRUCT = StructType(
        [
            StructField("assetCount", LongType(), True),
        ]
    )

    # CatalogModelDomainAllOfThumbnail.
    THUMBNAIL_STRUCT = StructType(
        [
            StructField("color", StringType(), True),
        ]
    )

    # CatalogModelRelatedCollectionParentCollection.
    PARENT_COLLECTION_STRUCT = StructType(
        [
            StructField("refName", StringType(), True),
            StructField("type", StringType(), True),
        ]
    )

    # CatalogModelRelatedCollection.
    RELATED_COLLECTION_STRUCT = StructType(
        [
            StructField("name", StringType(), True),
            StructField("friendlyName", StringType(), True),
            StructField("parentCollection", PARENT_COLLECTION_STRUCT, True),
        ]
    )

    # CatalogModelPlatformDomain — a physical-platform mapping under a domain.
    PLATFORM_DOMAIN_STRUCT = StructType(
        [
            StructField("name", StringType(), True),
            StructField("friendlyName", StringType(), True),
            StructField("relatedCollections", ArrayType(RELATED_COLLECTION_STRUCT), True),
        ]
    )


    # =============================================================================
    # Table schemas
    # =============================================================================

    BUSINESS_DOMAINS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("name", StringType(), True),
            StructField("description", StringType(), True),
            StructField("parentId", StringType(), True),
            StructField("status", StringType(), True),
            StructField("type", StringType(), True),
            StructField("isRestricted", BooleanType(), True),
            StructField("thumbnail", THUMBNAIL_STRUCT, True),
            StructField("domains", ArrayType(PLATFORM_DOMAIN_STRUCT), True),
            StructField("managedAttributes", ArrayType(MANAGED_ATTRIBUTE_STRUCT), True),
            StructField("systemData", SYSTEM_DATA_STRUCT, True),
            StructField("purview_tenant_id", StringType(), False),
        ]
    )

    DATA_PRODUCTS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("name", StringType(), True),
            StructField("domain", StringType(), True),
            StructField("type", StringType(), True),
            StructField("description", StringType(), True),
            StructField("businessUse", StringType(), True),
            StructField("status", StringType(), True),
            StructField("endorsed", BooleanType(), True),
            StructField("updateFrequency", StringType(), True),
            StructField("sensitivityLabel", StringType(), True),
            StructField("audience", ArrayType(StringType()), True),
            StructField("dataQualityScore", DoubleType(), True),
            StructField("activeSubscriberCount", LongType(), True),
            StructField("contacts", CONTACTS_STRUCT, True),
            StructField("termsOfUse", ArrayType(EXTERNAL_LINK_STRUCT), True),
            StructField("documentation", ArrayType(EXTERNAL_LINK_STRUCT), True),
            StructField("managedAttributes", ArrayType(MANAGED_ATTRIBUTE_STRUCT), True),
            StructField("additionalProperties", ADDITIONAL_PROPERTIES_STRUCT, True),
            StructField("systemData", SYSTEM_DATA_STRUCT, True),
            # Top-level copy of systemData.lastModifiedAt, promoted so it can serve
            # as the cdc sequence_by column (SDP APPLY CHANGES cannot resolve a
            # nested/dotted sequence_by path — see CURSOR_FIELD note below).
            StructField("last_modified_at", StringType(), True),
            StructField("purview_tenant_id", StringType(), False),
        ]
    )

    TERMS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("name", StringType(), True),
            StructField("description", StringType(), True),
            StructField("domain", StringType(), True),
            StructField("status", StringType(), True),
            StructField("parentId", StringType(), True),
            StructField("isLeaf", BooleanType(), True),
            StructField("acronyms", ArrayType(StringType()), True),
            StructField("contacts", CONTACTS_STRUCT, True),
            StructField("resources", ArrayType(TERM_RESOURCE_STRUCT), True),
            StructField("managedAttributes", ArrayType(MANAGED_ATTRIBUTE_STRUCT), True),
            StructField("systemData", SYSTEM_DATA_STRUCT, True),
            # Top-level copy of systemData.lastModifiedAt (see DATA_PRODUCTS_SCHEMA).
            StructField("last_modified_at", StringType(), True),
            StructField("purview_tenant_id", StringType(), False),
        ]
    )


    TABLE_SCHEMAS: dict[str, StructType] = {
        "business_domains": BUSINESS_DOMAINS_SCHEMA,
        "data_products": DATA_PRODUCTS_SCHEMA,
        "terms": TERMS_SCHEMA,
    }


    # =============================================================================
    # Table metadata
    # =============================================================================

    # The source cursor lives at a nested path (``systemData.lastModifiedAt``), but
    # SDP's managed CDC (APPLY CHANGES) maps ``cursor_field`` to ``sequence_by`` and
    # cannot resolve a nested/dotted sequence_by path (SEQUENCE_BY_COLUMN_NOT_FOUND).
    # So the cdc readers promote that value to a top-level ``last_modified_at``
    # column (see the cdc schemas) and the cursor_field points at that. The
    # connector's own client-side incremental read still reads the nested value
    # directly (see ``_record_cursor``); this constant is only the declared
    # sequence_by column.
    CURSOR_FIELD = "last_modified_at"

    TABLE_METADATA: dict[str, dict] = {
        # Governance domains are a low-volume taxonomy that changes infrequently —
        # snapshotted in full each run (mirrors Collibra's ``domains``).
        "business_domains": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "data_products": {
            "primary_keys": ["id"],
            "cursor_field": CURSOR_FIELD,
            "ingestion_type": "cdc",
        },
        "terms": {
            "primary_keys": ["id"],
            "cursor_field": CURSOR_FIELD,
            "ingestion_type": "cdc",
        },
    }


    SUPPORTED_TABLES: list[str] = list(TABLE_SCHEMAS.keys())


    # =============================================================================
    # API + HTTP tuning
    # =============================================================================

    # Unified Catalog Data Governance data-plane API version (public preview).
    API_VERSION = "2026-03-20-preview"

    # Shared data-plane endpoint for the Unified Catalog (not per-account).
    DEFAULT_ENDPOINT = "https://api.purview-service.microsoft.com"

    # ``top`` page size for skip/top-paginated endpoints (dataProducts / terms).
    # The API does not document a hard max; 100 is a conservative default that
    # keeps well under the per-operation rate windows (100 req / 20 s).
    DEFAULT_PAGE_SIZE = 100
    MAX_PAGE_SIZE = 1000

    RETRIABLE_STATUS_CODES = {429, 500, 502, 503, 504}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 1.0  # seconds; doubled after each retry


    ########################################################
    # src/databricks/labs/community_connector/sources/microsoft_purview/microsoft_purview_utils.py
    ########################################################

    DEFAULT_TIMEOUT = 30  # seconds


    def request_with_retry(
        session: requests.Session,
        url: str,
        params: dict[str, str] | None = None,
        timeout: int = DEFAULT_TIMEOUT,
    ) -> requests.Response:
        """Issue a GET with exponential backoff on retriable status codes.

        Honors the ``Retry-After`` header when present, otherwise doubles the
        backoff (1, 2, 4, 8, 16 s). Always passes an explicit ``timeout``.
        """
        backoff = INITIAL_BACKOFF
        resp = None
        for attempt in range(MAX_RETRIES):
            resp = session.get(url, params=params, timeout=timeout)
            if resp.status_code not in RETRIABLE_STATUS_CODES:
                return resp

            if attempt < MAX_RETRIES - 1:
                retry_after = resp.headers.get("Retry-After")
                try:
                    wait = float(retry_after) if retry_after else backoff
                except (TypeError, ValueError):
                    wait = backoff
                time.sleep(wait)
                backoff *= 2

        return resp


    def api_get(
        session: requests.Session,
        url: str,
        params: dict[str, str] | None,
        label: str,
        timeout: int = DEFAULT_TIMEOUT,
    ) -> dict:
        """GET and return parsed JSON, raising RuntimeError on non-200 responses."""
        response = request_with_retry(session, url, params, timeout=timeout)
        if response.status_code != 200:
            raise RuntimeError(
                f"Microsoft Purview API error for {label}: "
                f"{response.status_code} {response.text}"
            )
        return response.json()


    def next_link_paginate(
        session: requests.Session,
        url: str,
        params: dict[str, str],
        label: str,
        records_key: str = "value",
        *,
        timeout: int = DEFAULT_TIMEOUT,
    ) -> Iterator[dict[str, Any]]:
        """Yield records from a ``nextLink``-paginated Unified Catalog endpoint.

        The first request uses ``url`` + ``params``; every subsequent page follows
        the absolute ``nextLink`` URL from the previous ``PagedX`` body (which
        already embeds ``api-version``, ``$skipToken``/``skip``, and any filters),
        so ``params`` is only applied to the first call. Stops when ``nextLink`` is
        absent or a page is empty.

        Used for ``businessdomains`` (``$skipToken`` continuation), ``dataProducts``
        and ``terms`` (``skip``/``top``) — all three share the ``{value, nextLink}``
        envelope.
        """
        page_params: dict[str, str] | None = dict(params)
        next_url: str | None = url
        while next_url:
            body = api_get(session, next_url, page_params, label, timeout=timeout)
            batch = body.get(records_key) or []
            yield from batch

            next_url = body.get("nextLink")
            # nextLink is a fully-formed absolute URL; don't re-apply query params.
            page_params = None
            if not batch:
                break


    def normalize_contacts(value: Any) -> dict[str, Any] | None:
        """Normalize a ``ContactsMap`` to the declared struct shape.

        Keeps only the declared roles (``owner`` / ``expert`` / ``databaseAdmin``)
        and coerces each contact to ``{id, description}`` so unexpected API keys
        don't break schema coercion. Returns ``None`` for an absent/empty map so
        the field maps cleanly onto the nullable struct.
        """
        if not isinstance(value, dict) or not value:
            return None
        out: dict[str, Any] = {}
        for role in ("owner", "expert", "databaseAdmin"):
            entries = value.get(role)
            if isinstance(entries, list):
                out[role] = [
                    {"id": c.get("id"), "description": c.get("description")}
                    for c in entries
                    if isinstance(c, dict)
                ]
            else:
                out[role] = None
        return out


    ########################################################
    # src/databricks/labs/community_connector/sources/microsoft_purview/microsoft_purview.py
    ########################################################

    _LOG = logging.getLogger(__name__)

    DEFAULT_MAX_RECORDS_PER_BATCH = 5000

    # Catalog path prefixes (relative to the data-plane endpoint).
    _CATALOG_BASE = "/datagovernance/catalog"


    class MicrosoftPurviewLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for the Purview Unified Catalog API."""

        def __init__(self, options: dict[str, str]) -> None:
            """Initialize the Microsoft Purview connector.

            Expected options:
                - tenant_id: Azure Entra (AAD) tenant ID/GUID. Used for row
                  disambiguation and (server-side, by UC) as the token-endpoint
                  interpolation value. Required.
                - endpoint: Unified Catalog data-plane base URL. Defaults to the
                  shared ``https://api.purview-service.microsoft.com``.
                - access_token: OAuth 2.0 bearer token, minted and injected by the
                  UC COMMUNITY connection (m2m / client-credentials).
                - token: personal/API token fallback used the same way as
                  ``access_token`` (``Authorization: Bearer``) for ad-hoc use.
                - page_size: ``top`` page size for skip/top-paginated endpoints.
            """
            super().__init__(options)

            self.tenant_id = options.get("tenant_id") or options.get("account")
            if not self.tenant_id:
                raise ValueError(
                    "Microsoft Purview connector requires 'tenant_id' (Azure "
                    "Entra tenant ID)"
                )

            endpoint = options.get("endpoint") or DEFAULT_ENDPOINT
            self.endpoint = endpoint.rstrip("/")

            try:
                self._page_size = max(
                    1,
                    min(
                        MAX_PAGE_SIZE,
                        int(options.get("page_size") or DEFAULT_PAGE_SIZE),
                    ),
                )
            except (TypeError, ValueError):
                self._page_size = DEFAULT_PAGE_SIZE

            self._session = requests.Session()
            self._session.headers.update({"Accept": "application/json"})
            self._configure_auth(options)

            # Cap incremental cursors at init time so a single Trigger.AvailableNow
            # run only drains data that existed when the connector started; data
            # modified after this point is picked up by the next trigger with a
            # fresh _init_ts. This is the termination guard. ISO-8601 UTC string to
            # match the systemData.lastModifiedAt cursor unit (ISO strings compare
            # lexicographically).
            self._init_ts = datetime.now(timezone.utc).isoformat()

        def _configure_auth(self, options: dict[str, str]) -> None:
            """Set the Bearer auth header from the injected token.

            ``access_token`` (OAuth m2m, UC-injected) takes precedence; ``token``
            is an equivalent personal-token fallback. The connector never runs the
            OAuth client-credentials exchange itself — that is offloaded to Unity
            Catalog, mirroring the Azure DevOps ``service_principal`` model.
            """
            access_token = options.get("access_token") or options.get("token")
            if not access_token:
                raise ValueError(
                    "Microsoft Purview connector requires 'access_token' (OAuth "
                    "m2m bearer token, injected by the UC connection) or 'token'"
                )
            self._session.headers["Authorization"] = f"Bearer {access_token}"

        # ------------------------------------------------------------------ #
        # Interface methods
        # ------------------------------------------------------------------ #

        def list_tables(self) -> list[str]:
            return list(SUPPORTED_TABLES)

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            self._validate_table(table_name)
            return dict(TABLE_METADATA[table_name])

        def read_table(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            self._validate_table(table_name)
            if table_name == "business_domains":
                return self._read_business_domains(table_options)
            if table_name == "data_products":
                return self._read_data_products(start_offset, table_options)
            if table_name == "terms":
                return self._read_terms(start_offset, table_options)
            raise ValueError(f"Unsupported table: {table_name!r}")

        # ------------------------------------------------------------------ #
        # Table readers
        # ------------------------------------------------------------------ #

        def _read_business_domains(
            self, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read business (governance) domains as a snapshot.

            The businessdomains endpoint paginates via a ``$skipToken`` embedded in
            ``nextLink``; ``next_link_paginate`` follows it transparently.
            """
            params = {"api-version": API_VERSION}
            if table_options.get("write_only"):
                params["writeOnly"] = table_options["write_only"]

            url = f"{self.endpoint}{_CATALOG_BASE}/businessdomains"
            records: list[dict[str, Any]] = []
            for raw in next_link_paginate(self._session, url, params, "business_domains"):
                records.append(self._shape_business_domain(raw))
            return iter(records), {}

        def _read_data_products(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read data products incrementally on ``systemData.lastModifiedAt``.

            Paginated by ``skip`` / ``top`` with a ``nextLink`` follow. Optional
            ``domain_id`` scopes to a single governance domain.
            """
            params = {"api-version": API_VERSION, "top": str(self._page_size)}
            if table_options.get("domain_id"):
                params["domainId"] = table_options["domain_id"]
            if table_options.get("order_by"):
                params["orderBy"] = table_options["order_by"]

            url = f"{self.endpoint}{_CATALOG_BASE}/dataProducts"
            record_iter = next_link_paginate(self._session, url, params, "data_products")
            return self._incremental_from_iter(
                record_iter, start_offset, transform=self._shape_data_product
            )

        def _read_terms(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read glossary terms incrementally on ``systemData.lastModifiedAt``.

            Paginated by ``skip`` / ``top`` with a ``nextLink`` follow. Optional
            ``domain_id`` / ``parent_id`` / ``keyword`` narrow the extract.
            """
            params = {"api-version": API_VERSION, "top": str(self._page_size)}
            if table_options.get("domain_id"):
                params["domainId"] = table_options["domain_id"]
            if table_options.get("parent_id"):
                params["parentId"] = table_options["parent_id"]
            if table_options.get("keyword"):
                params["keyword"] = table_options["keyword"]
            if table_options.get("order_by"):
                params["orderBy"] = table_options["order_by"]

            url = f"{self.endpoint}{_CATALOG_BASE}/terms"
            record_iter = next_link_paginate(self._session, url, params, "terms")
            return self._incremental_from_iter(
                record_iter, start_offset, transform=self._shape_term
            )

        # ------------------------------------------------------------------ #
        # Incremental engine
        # ------------------------------------------------------------------ #

        def _incremental_from_iter(
            self,
            record_iter: Iterator[dict[str, Any]],
            start_offset: dict,
            transform,
        ) -> tuple[Iterator[dict], dict]:
            """Apply the client-side incremental cursor over a record iterator.

            Applies, per record:
              * inclusive ``>= since`` filtering (skip only strictly-older records)
                so same-second records straddling a run boundary are not lost — the
                cursor is second-granular, so a strict ``>`` would permanently drop a
                record sharing the watermark second that arrives after the watermark
                reached it; boundary rows are re-emitted and deduped by the CDC
                primary-key upsert, and
              * an init-time upper cap (skip records modified after
                ``self._init_ts``) so Trigger.AvailableNow terminates.

            The Unified Catalog list endpoints do not accept a server-side
            modified-since filter, and ``orderBy`` on the nested
            ``systemData/lastModifiedAt`` path is unverified against a live tenant,
            so records are treated as **not** cursor-sorted: we drain the full
            collection per run (bounded only by the ``self._init_ts`` cap) rather
            than truncating by count on an unordered slice. Count-based truncation
            of an unordered slice would advance the watermark to an arbitrary max
            and silently drop not-yet-seen records at or below it. CDC upsert on
            the primary key tolerates the resulting re-reads. (needs-live-testing:
            once ``orderBy=systemData/lastModifiedAt asc`` is confirmed, this can
            switch to a soft, tie-group-aware count cap like Collibra's sorted
            path.)

            Returns ``(records, end_offset)``. When nothing new is emitted, the
            offset is returned unchanged so ``end_offset == start_offset`` and the
            trigger converges.
            """
            start_offset = start_offset or {}
            since = start_offset.get("cursor")

            # Already caught up to init time — nothing new can be emitted.
            if since is not None and since >= self._init_ts:
                return iter([]), start_offset

            records: list[dict[str, Any]] = []
            max_seen = since
            for raw in record_iter:
                cursor = self._record_cursor(raw)
                # Inclusive `>=` boundary (skip only strictly-older records). The
                # cursor's smallest unit is a *second* (systemData.lastModifiedAt),
                # so several records can share the exact boundary value. A strict `>`
                # would permanently drop any same-second record that lands after a
                # prior run already advanced the watermark to that second. Re-emitting
                # the boundary second each run is safe: CDC upserts on the primary key
                # (`id`), so re-read boundary rows are deduped, not duplicated. The
                # cost is bounded (only rows at exactly the max second) and the offset
                # still cannot advance past `_init_ts`, so triggers converge.
                if since is not None and cursor is not None and cursor < since:
                    continue
                # Init-time cap: skip records modified after the connector started.
                if cursor is not None and cursor > self._init_ts:
                    continue

                records.append(transform(raw))
                if cursor is not None and (max_seen is None or cursor > max_seen):
                    max_seen = cursor

            if not records or max_seen is None or max_seen == since:
                # No forward progress — return the offset unchanged so the
                # framework sees end_offset == start_offset and terminates.
                return iter(records), start_offset

            return iter(records), {"cursor": max_seen}

        @staticmethod
        def _record_cursor(raw: dict[str, Any]) -> str | None:
            """Extract the ``systemData.lastModifiedAt`` cursor value from a record.

            Returns the ISO-8601 string, or ``None`` when absent so it is treated
            as uncomparable and never breaks ordering.
            """
            system_data = raw.get("systemData")
            if isinstance(system_data, dict):
                value = system_data.get("lastModifiedAt")
                if isinstance(value, str) and value:
                    return value
            return None

        # ------------------------------------------------------------------ #
        # Record shaping
        # ------------------------------------------------------------------ #

        def _shape_business_domain(self, raw: dict[str, Any]) -> dict[str, Any]:
            rec = dict(raw)
            rec["purview_tenant_id"] = self.tenant_id
            return rec

        def _shape_data_product(self, raw: dict[str, Any]) -> dict[str, Any]:
            rec = dict(raw)
            rec["contacts"] = normalize_contacts(raw.get("contacts"))
            # Promote the nested cursor to a top-level column for cdc sequence_by.
            rec["last_modified_at"] = self._record_cursor(raw)
            rec["purview_tenant_id"] = self.tenant_id
            return rec

        def _shape_term(self, raw: dict[str, Any]) -> dict[str, Any]:
            rec = dict(raw)
            rec["contacts"] = normalize_contacts(raw.get("contacts"))
            # Promote the nested cursor to a top-level column for cdc sequence_by.
            rec["last_modified_at"] = self._record_cursor(raw)
            rec["purview_tenant_id"] = self.tenant_id
            return rec

        # ------------------------------------------------------------------ #
        # Helpers
        # ------------------------------------------------------------------ #

        def _validate_table(self, table_name: str) -> None:
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(
                    f"Unsupported table {table_name!r}; "
                    f"supported: {SUPPORTED_TABLES}"
                )


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = MicrosoftPurviewLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
