"""Regression test generated by Connector Doctor for azure_devops — class L
(error reporting): a non-200 from the Azure DevOps API must SURFACE as a raised
error carrying the real status, body, and table label — never a swallowed
None/empty. Offline: no creds, no network.

Demonstrates the reusable regression-test template on a second connector (the
same pattern that guarded the HubSpot masked-error bug).
"""

import pytest

from databricks.labs.community_connector.sources.azure_devops.azure_devops_utils import (
    api_get,
)


class _FaultResponse:
    status_code = 401  # non-retriable -> no backoff sleeps
    text = "unauthorized: token invalid"

    def json(self):
        return {}


class _FakeSession:
    def get(self, url, params=None, timeout=None):
        return _FaultResponse()


def test_api_get_surfaces_error_detail():
    with pytest.raises(RuntimeError) as excinfo:
        api_get(_FakeSession(), "https://dev.azure.com/org/_apis/git", {}, "commits")

    msg = str(excinfo.value)
    assert "401" in msg          # real status surfaces
    assert "unauthorized" in msg  # real body surfaces
    assert "commits" in msg       # the table label surfaces
